ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS poll_type text NOT NULL DEFAULT 'solo' CHECK (poll_type IN ('solo','pair','parts'));
ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS part_a text NOT NULL DEFAULT 'Part A';
ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS part_b text NOT NULL DEFAULT 'Part B';
ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS part_locks text NOT NULL DEFAULT '{}';

CREATE TABLE IF NOT EXISTS cucac.duet_entries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phase_id integer NOT NULL REFERENCES cucac.phases(id) ON DELETE CASCADE,
  member1 integer NOT NULL REFERENCES cucac.users(id) ON DELETE CASCADE,
  member2 integer REFERENCES cucac.users(id) ON DELETE CASCADE,
  proposed_by integer NOT NULL REFERENCES cucac.users(id) ON DELETE CASCADE,
  part text NOT NULL CHECK (part IN ('pair','A','B')),
  confirmed integer NOT NULL DEFAULT 0 CHECK (confirmed IN (0,1)),
  audition_url text NOT NULL DEFAULT '',
  created_at text NOT NULL,
  UNIQUE(phase_id,id),
  CHECK ((part='pair' AND member2 IS NOT NULL AND member1<member2) OR (part IN ('A','B') AND member2 IS NULL AND confirmed=1))
);
CREATE UNIQUE INDEX IF NOT EXISTS duet_pair_unique ON cucac.duet_entries(phase_id,member1,member2) WHERE part='pair';
CREATE UNIQUE INDEX IF NOT EXISTS duet_part_unique ON cucac.duet_entries(phase_id,member1) WHERE part IN ('A','B');
CREATE INDEX IF NOT EXISTS duet_entries_member2 ON cucac.duet_entries(member2);
CREATE INDEX IF NOT EXISTS duet_entries_proposer ON cucac.duet_entries(proposed_by);
CREATE INDEX IF NOT EXISTS duet_entries_member1 ON cucac.duet_entries(member1);

CREATE TABLE IF NOT EXISTS cucac.duet_votes (
  phase_id integer NOT NULL,
  entry_id integer NOT NULL,
  voter_id integer NOT NULL REFERENCES cucac.users(id) ON DELETE CASCADE,
  PRIMARY KEY(phase_id,voter_id,entry_id),
  FOREIGN KEY(phase_id,entry_id) REFERENCES cucac.duet_entries(phase_id,id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS duet_votes_entry ON cucac.duet_votes(phase_id,entry_id);
CREATE INDEX IF NOT EXISTS duet_votes_voter ON cucac.duet_votes(voter_id);
ALTER TABLE cucac.duet_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE cucac.duet_votes ENABLE ROW LEVEL SECURITY;
