CREATE TABLE IF NOT EXISTS cucac.plan_terms (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 label text NOT NULL UNIQUE,
 archived boolean NOT NULL DEFAULT false,
 roster_snapshot jsonb,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS plan_terms_label_ci ON cucac.plan_terms(lower(label));
CREATE TABLE IF NOT EXISTS cucac.plan_songs (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 term_id integer NOT NULL REFERENCES cucac.plan_terms(id) ON DELETE CASCADE,
 title text NOT NULL,
 folder_url text NOT NULL DEFAULT '',
 locked boolean NOT NULL DEFAULT false,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS plan_songs_term_idx ON cucac.plan_songs(term_id);
CREATE TABLE IF NOT EXISTS cucac.plan_entries (
 song_id integer NOT NULL REFERENCES cucac.plan_songs(id) ON DELETE CASCADE,
 member_key integer NOT NULL,
 member_id integer REFERENCES cucac.users(id) ON DELETE SET NULL,
 member_name text NOT NULL,
 part text NOT NULL CHECK(part IN ('soprano','alto','tenor','baritone','bass','bbox','rap')),
 created_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(song_id,member_key)
);
CREATE INDEX IF NOT EXISTS plan_entries_member_idx ON cucac.plan_entries(member_id);
ALTER TABLE cucac.plan_terms ENABLE ROW LEVEL SECURITY;
ALTER TABLE cucac.plan_songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE cucac.plan_entries ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON cucac.plan_terms,cucac.plan_songs,cucac.plan_entries FROM anon; END IF; IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON cucac.plan_terms,cucac.plan_songs,cucac.plan_entries FROM authenticated; END IF; END $$;
INSERT INTO cucac.plan_terms(label) VALUES('2026 Fall') ON CONFLICT(label) DO NOTHING;
