CREATE TABLE IF NOT EXISTS cucac.plan_sheet_jobs (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 folder_id text NOT NULL,
 semester text NOT NULL,
 title text NOT NULL,
 synced boolean NOT NULL DEFAULT false,
 last_error text NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(folder_id,semester)
);
CREATE INDEX IF NOT EXISTS plan_sheet_jobs_pending ON cucac.plan_sheet_jobs(id) WHERE NOT synced;
ALTER TABLE cucac.plan_sheet_jobs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON cucac.plan_sheet_jobs FROM anon; END IF; IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON cucac.plan_sheet_jobs FROM authenticated; END IF; END $$;
