CREATE SCHEMA IF NOT EXISTS cucac;

SET search_path TO cucac, public;

CREATE TABLE "users" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"password_hash" text NOT NULL,
	"created_at" text NOT NULL,
	"is_admin" integer DEFAULT 0 NOT NULL,
	"can_start" integer DEFAULT 0 NOT NULL,
	"is_md" integer DEFAULT 0 NOT NULL,
	"is_arranger" integer DEFAULT 0 NOT NULL,
	"is_alumni" integer DEFAULT 0 NOT NULL,
	"is_president" integer DEFAULT 0 NOT NULL,
	"is_vp" integer DEFAULT 0 NOT NULL,
	"is_secretary" integer DEFAULT 0 NOT NULL,
	"is_treasurer" integer DEFAULT 0 NOT NULL,
	"is_media" integer DEFAULT 0 NOT NULL,
	"full_name" text DEFAULT '' NOT NULL,
	"pronouns" text DEFAULT '' NOT NULL,
	"position" text DEFAULT '' NOT NULL,
	"voice_part" text DEFAULT '' NOT NULL,
	"school" text DEFAULT '' NOT NULL,
	"grad_year" text DEFAULT '' NOT NULL,
	"program" text DEFAULT '' NOT NULL,
	"fun_fact" text DEFAULT '' NOT NULL,
	"favorite_food" text DEFAULT '' NOT NULL,
	"avatar_ext" text DEFAULT '' NOT NULL,
 "avatar_photo_id" text,
 "gallery_seeded" integer DEFAULT 0 NOT NULL
);

CREATE TABLE "sessions" (
	"token" text PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"created_at" text NOT NULL,
	FOREIGN KEY ("user_id") REFERENCES "users"("id") ON UPDATE no action ON DELETE no action
);

CREATE TABLE "phases" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"status" text NOT NULL,
	"created_by" integer NOT NULL,
	"created_at" text NOT NULL,
	"closed_at" text,
	"arranger_id" integer,
	FOREIGN KEY ("created_by") REFERENCES "users"("id") ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("arranger_id") REFERENCES "users"("id") ON UPDATE no action ON DELETE no action,
	CONSTRAINT "phase_status" CHECK("phases"."status" in ('open', 'closed'))
);

CREATE TABLE "candidacies" (
	"phase_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"created_at" text NOT NULL,
	PRIMARY KEY("phase_id", "user_id"),
	FOREIGN KEY ("phase_id") REFERENCES "phases"("id") ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("user_id") REFERENCES "users"("id") ON UPDATE no action ON DELETE no action
);

CREATE TABLE "votes" (
	"phase_id" integer NOT NULL,
	"voter_id" integer NOT NULL,
	"candidate_id" integer NOT NULL,
	"reaction" text NOT NULL,
	PRIMARY KEY("phase_id", "voter_id", "candidate_id"),
	FOREIGN KEY ("phase_id") REFERENCES "phases"("id") ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("voter_id") REFERENCES "users"("id") ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("candidate_id") REFERENCES "users"("id") ON UPDATE no action ON DELETE no action,
	CONSTRAINT "vote_reaction" CHECK("votes"."reaction" in ('like', 'again'))
);

CREATE TABLE "arrangers" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"created_at" text NOT NULL
);

CREATE TABLE "semesters" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"label" text NOT NULL,
	"folder_id" text NOT NULL,
	"created_at" text NOT NULL
);

CREATE TABLE "scores" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"arranger" text NOT NULL,
	"kind" text NOT NULL,
	"semester_id" integer,
	"semester_label" text NOT NULL,
	"file_name" text NOT NULL,
	"drive_file_id" text,
	"drive_url" text,
	"uploaded_by" integer NOT NULL,
	"created_at" text NOT NULL,
	"kinds" text DEFAULT '' NOT NULL,
	FOREIGN KEY ("semester_id") REFERENCES "semesters"("id") ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON UPDATE no action ON DELETE no action,
	CONSTRAINT "score_kind" CHECK("scores"."kind" in ('big', 'small'))
);

CREATE TABLE "photos" (
	"id" text PRIMARY KEY NOT NULL,
	"owner_id" integer NOT NULL,
	"uploaded_by" integer,
	"ext" text NOT NULL,
	"created_at" text NOT NULL,
	FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON UPDATE no action ON DELETE set null
);

CREATE UNIQUE INDEX "arrangers_name_unique" ON "arrangers" (lower("name"));

CREATE UNIQUE INDEX "one_open_phase" ON "phases" ("status") WHERE "phases"."status" = 'open';

CREATE UNIQUE INDEX "semesters_label_unique" ON "semesters" (lower("label"));

CREATE UNIQUE INDEX "users_name_unique" ON "users" (lower("name"));

CREATE INDEX "idx_photos_owner_created" ON "photos" ("owner_id","created_at");

CREATE TABLE invitations (id text PRIMARY KEY, code_hash text UNIQUE NOT NULL, created_by integer REFERENCES users(id) ON DELETE SET NULL, created_at text NOT NULL, expires_at text NOT NULL, used_by integer REFERENCES users(id) ON DELETE SET NULL, used_at text, revoked integer NOT NULL DEFAULT 0);

ALTER TABLE arrangers ENABLE ROW LEVEL SECURITY;

ALTER TABLE candidacies ENABLE ROW LEVEL SECURITY;

ALTER TABLE phases ENABLE ROW LEVEL SECURITY;

ALTER TABLE scores ENABLE ROW LEVEL SECURITY;

ALTER TABLE semesters ENABLE ROW LEVEL SECURITY;

ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

ALTER TABLE users ENABLE ROW LEVEL SECURITY;

ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

ALTER TABLE photos ENABLE ROW LEVEL SECURITY;

ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON SCHEMA cucac FROM anon; END IF; IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON SCHEMA cucac FROM authenticated; END IF; END $$;

ALTER TABLE cucac.invitations ADD COLUMN IF NOT EXISTS is_shared integer NOT NULL DEFAULT 0 CHECK (is_shared IN (0,1));
ALTER TABLE cucac.invitations ADD COLUMN IF NOT EXISTS use_count integer NOT NULL DEFAULT 0 CHECK (use_count >= 0);

ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS voting_mode text NOT NULL DEFAULT 'feedback' CHECK(voting_mode IN ('default','feedback'));
ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS started_at text;
ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS registration_locked integer NOT NULL DEFAULT 0;
ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS candidate_order text NOT NULL DEFAULT '[]';
ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS revealed_ranks integer NOT NULL DEFAULT 2 CHECK(revealed_ranks>=2);
-- Existing rounds retain the old feedback mechanism and remain available for voting.
UPDATE cucac.phases SET started_at=created_at WHERE voting_mode='feedback' AND started_at IS NULL;

ALTER TABLE cucac.users ADD COLUMN IF NOT EXISTS is_crew integer NOT NULL DEFAULT 0 CHECK (is_crew IN (0,1));

ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS poll_type text NOT NULL DEFAULT 'solo' CHECK (poll_type IN ('solo','pair','parts'));
ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS part_a text NOT NULL DEFAULT 'Part A';
ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS part_b text NOT NULL DEFAULT 'Part B';
ALTER TABLE cucac.phases ADD COLUMN IF NOT EXISTS part_locks text NOT NULL DEFAULT '{}';

CREATE TABLE IF NOT EXISTS cucac.duet_entries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phase_id integer NOT NULL REFERENCES cucac.phases(id) ON DELETE CASCADE,
  member1 integer NOT NULL REFERENCES cucac.users(id) ON DELETE CASCADE,
  member2 integer REFERENCES cucac.users(id) ON DELETE CASCADE,
  proposed_by integer NOT NULL REFERENCES cucac.users(id) ON DELETE CASCADE,
  part text NOT NULL CHECK (part IN ('pair','A','B')),
  confirmed integer NOT NULL DEFAULT 0 CHECK (confirmed IN (0,1)),
  audition_url text NOT NULL DEFAULT '',
  created_at text NOT NULL,
  UNIQUE(phase_id,id),
  CHECK ((part='pair' AND member2 IS NOT NULL AND member1<member2) OR (part IN ('A','B') AND member2 IS NULL AND confirmed=1))
);
CREATE UNIQUE INDEX IF NOT EXISTS duet_pair_unique ON cucac.duet_entries(phase_id,member1,member2) WHERE part='pair';
CREATE UNIQUE INDEX IF NOT EXISTS duet_part_unique ON cucac.duet_entries(phase_id,member1) WHERE part IN ('A','B');
CREATE INDEX IF NOT EXISTS duet_entries_member2 ON cucac.duet_entries(member2);
CREATE INDEX IF NOT EXISTS duet_entries_proposer ON cucac.duet_entries(proposed_by);
CREATE INDEX IF NOT EXISTS duet_entries_member1 ON cucac.duet_entries(member1);

CREATE TABLE IF NOT EXISTS cucac.duet_votes (
  phase_id integer NOT NULL,
  entry_id integer NOT NULL,
  voter_id integer NOT NULL REFERENCES cucac.users(id) ON DELETE CASCADE,
  PRIMARY KEY(phase_id,voter_id,entry_id),
  FOREIGN KEY(phase_id,entry_id) REFERENCES cucac.duet_entries(phase_id,id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS duet_votes_entry ON cucac.duet_votes(phase_id,entry_id);
CREATE INDEX IF NOT EXISTS duet_votes_voter ON cucac.duet_votes(voter_id);
ALTER TABLE cucac.duet_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE cucac.duet_votes ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS cucac.recordings (
 id text PRIMARY KEY,
 phase_id integer REFERENCES cucac.phases(id) ON DELETE SET NULL,
 candidate_id integer REFERENCES cucac.users(id) ON DELETE SET NULL,
 entry_id integer REFERENCES cucac.duet_entries(id) ON DELETE SET NULL,
 uploaded_by integer REFERENCES cucac.users(id) ON DELETE SET NULL,
 object_key text NOT NULL UNIQUE,
 mime text NOT NULL,
 size integer NOT NULL DEFAULT 0,
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','ready')),
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS recordings_phase ON cucac.recordings(phase_id);
CREATE INDEX IF NOT EXISTS recordings_candidate ON cucac.recordings(candidate_id);
CREATE INDEX IF NOT EXISTS recordings_entry ON cucac.recordings(entry_id);
CREATE INDEX IF NOT EXISTS recordings_uploader ON cucac.recordings(uploaded_by);
ALTER TABLE cucac.recordings ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS cucac.plan_terms (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 label text NOT NULL UNIQUE,
 archived boolean NOT NULL DEFAULT false,
 roster_snapshot jsonb,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS plan_terms_label_ci ON cucac.plan_terms(lower(label));
CREATE TABLE IF NOT EXISTS cucac.plan_songs (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 term_id integer NOT NULL REFERENCES cucac.plan_terms(id) ON DELETE CASCADE,
 title text NOT NULL,
 folder_url text NOT NULL DEFAULT '',
 locked boolean NOT NULL DEFAULT false,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS plan_songs_term_idx ON cucac.plan_songs(term_id);
CREATE TABLE IF NOT EXISTS cucac.plan_entries (
 song_id integer NOT NULL REFERENCES cucac.plan_songs(id) ON DELETE CASCADE,
 member_key integer NOT NULL,
 member_id integer REFERENCES cucac.users(id) ON DELETE SET NULL,
 member_name text NOT NULL,
 part text NOT NULL CHECK(part IN ('soprano','alto','tenor','baritone','bass','bbox','rap')),
 created_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(song_id,member_key)
);
CREATE INDEX IF NOT EXISTS plan_entries_member_idx ON cucac.plan_entries(member_id);
ALTER TABLE cucac.plan_terms ENABLE ROW LEVEL SECURITY;
ALTER TABLE cucac.plan_songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE cucac.plan_entries ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON cucac.plan_terms,cucac.plan_songs,cucac.plan_entries FROM anon; END IF; IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON cucac.plan_terms,cucac.plan_songs,cucac.plan_entries FROM authenticated; END IF; END $$;
INSERT INTO cucac.plan_terms(label) VALUES('2026 Fall') ON CONFLICT(label) DO NOTHING;

CREATE TABLE IF NOT EXISTS cucac.plan_sheet_jobs (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 folder_id text NOT NULL,
 semester text NOT NULL,
 title text NOT NULL,
 synced boolean NOT NULL DEFAULT false,
 last_error text NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(folder_id,semester)
);
CREATE INDEX IF NOT EXISTS plan_sheet_jobs_pending ON cucac.plan_sheet_jobs(id) WHERE NOT synced;
ALTER TABLE cucac.plan_sheet_jobs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON cucac.plan_sheet_jobs FROM anon; END IF; IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON cucac.plan_sheet_jobs FROM authenticated; END IF; END $$;

ALTER TABLE cucac.plan_songs ADD COLUMN IF NOT EXISTS excluded boolean NOT NULL DEFAULT false;

ALTER TABLE cucac.plan_terms ADD COLUMN IF NOT EXISTS is_current boolean NOT NULL DEFAULT false;
CREATE UNIQUE INDEX IF NOT EXISTS plan_one_current_term ON cucac.plan_terms(is_current) WHERE is_current;
UPDATE cucac.plan_terms SET is_current=true WHERE id=(SELECT id FROM cucac.plan_terms WHERE NOT archived ORDER BY created_at DESC,id DESC LIMIT 1) AND NOT EXISTS(SELECT 1 FROM cucac.plan_terms WHERE is_current);
CREATE TABLE IF NOT EXISTS cucac.plan_cast (
 song_id integer NOT NULL REFERENCES cucac.plan_songs(id) ON DELETE CASCADE,
 member_key integer NOT NULL,
 member_id integer REFERENCES cucac.users(id) ON DELETE SET NULL,
 member_name text NOT NULL,
 part text NOT NULL CHECK(part IN ('solo','soprano','alto','tenor','baritone','bass','bbox','rap')),
 created_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(song_id,member_key,part)
);
CREATE INDEX IF NOT EXISTS plan_cast_member_idx ON cucac.plan_cast(member_id);
ALTER TABLE cucac.plan_cast ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON cucac.plan_cast FROM anon; END IF; IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON cucac.plan_cast FROM authenticated; END IF; END $$;
INSERT INTO cucac.plan_cast(song_id,member_key,member_id,member_name,part,created_at) SELECT song_id,member_key,member_id,member_name,part,created_at FROM cucac.plan_entries ON CONFLICT(song_id,member_key,part) DO NOTHING;

ALTER TABLE cucac.plan_songs ADD COLUMN IF NOT EXISTS big_song boolean NOT NULL DEFAULT false;
