import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {createDatabase} from '../vercel/database.js';
import {createVoting} from '../vercel/voting.js';
import {createInvitations} from '../vercel/invitations.js';
import {createRecordings} from '../vercel/recordings.js';
import worker from '../dist/vercel-worker.mjs';
const postgres=new PGlite();
await postgres.exec(fs.readFileSync('vercel/schema.sql','utf8'));
const query=async(sql,args=[])=>{const r=await postgres.query(sql,args);return {rows:r.rows,rowCount:r.affectedRows??r.rows.length};};
const pool={query,connect:async()=>({query,release(){}})};
const files=new Map();
const storage={async get(key){const v=files.get(key);return v?{async arrayBuffer(){return v.buffer.slice(v.byteOffset,v.byteOffset+v.byteLength)},async text(){return v.toString()},async json(){return JSON.parse(v.toString())}}:null},async put(key,value){files.set(key,Buffer.from(typeof value==='string'?value:await new Response(value).arrayBuffer()))},async delete(key){files.delete(key)}};
const env={DB:createDatabase(pool),FILES:storage,ADMIN_PASSWORD:'test-admin-password',PUBLIC_ORIGIN:'https://hub.test',INVITE_REQUIRED:true,invitations:createInvitations(pool),voting:createVoting(pool)};
env.recordings=createRecordings(pool,{...storage,audioUploadUrl:async key=>'https://storage.test/upload/'+key,audioInfo:async key=>({size:files.get(key)?.length||0,contentType:'audio/webm'}),audioPlaybackUrl:async key=>'https://storage.test/play/'+key});
const mf={dispatchFetch:(url,options)=>worker.fetch(new Request(url,options),env),getR2Bucket:async()=>storage,dispose:async()=>postgres.close()};
try {
 const cookies={};
 async function api(path, who='',body=undefined,status=200){
  if(path==='/api/register'&&status===201&&!body.invitationCode)body={...body,invitationCode:(await api('/api/admin/invitations','admin',{},201)).code};
  const headers={};if(who&&cookies[who])headers.Cookie=cookies[who];if(body!==undefined)headers['Content-Type']='application/json';
  const res=await mf.dispatchFetch('https://hub.test'+path,{method:body!==undefined?'POST':'GET',headers,body:body!==undefined?JSON.stringify(body):undefined});
  const raw=await res.text();assert.equal(res.status,status,`${path}: ${raw}`);const set=res.headers.get('set-cookie');if(set&&who)cookies[who]=set.split(';')[0];return raw?JSON.parse(raw):null;
 }
 const home=await mf.dispatchFetch('https://hub.test/');assert.equal(home.status,200);assert.match(await home.text(),/solo|阿卡贝拉/i);
 await api('/api/state','',undefined,401);
 const admin=await api('/api/login','admin',{name:'admin',password:'test-admin-password'});assert.equal(admin.user.isAdmin,true);
 const md=await api('/api/register','md',{name:'Jingwen',password:'abc12345'},201);
 const member=await api('/api/register','member',{name:'Singer',password:'abc12345'},201);
 await api('/api/register','duplicate',{name:'Jingwen',password:'abc12345'},409);
 await api('/api/login','bad',{name:'Jingwen',password:'wrong'},401);
 await api(`/api/admin/users/${md.user.id}`,'admin',{musicDirector:true,arranger:true});
 // Multi-part profiles, canonical ordering, and narrowly scoped President/MD delegation.
 let voices=await api(`/api/members/${member.user.id}/voice-parts`,'member',{voiceParts:['rap','alto','alto']});
 assert.deepEqual(voices.profile.voiceParts,['alto','rap']);
 await api(`/api/members/${md.user.id}/voice-parts`,'member',{voiceParts:['bass']},403);
 await api(`/api/members/${member.user.id}/voice-parts`,'md',{voiceParts:['tenor','bbox']});
 await api(`/api/members/${member.user.id}/voice-parts`,'member',{voiceParts:['unknown']},400);
 await api(`/api/admin/users/${member.user.id}`,'admin',{president:true});
 voices=await api(`/api/members/${md.user.id}/voice-parts`,'member',{voiceParts:['soprano','alto']});
 assert.deepEqual(voices.members.find(p=>p.id===md.user.id).voiceParts,['soprano','alto']);
 await api(`/api/admin/users/${member.user.id}`,'admin',{president:false});
 await api(`/api/members/${md.user.id}/voice-parts`,'member',{voiceParts:['bass']},403);
 await api('/api/profile','member',{fullName:'Singer',voiceParts:['baritone','bass','bbox','rap']});
 assert.deepEqual((await api('/api/state','member')).profile.voiceParts,['baritone','bass','bbox','rap']);
 console.log('PASS: multi-part profiles, canonical values, duplicate removal, invalid-part rejection, and President/MD-only editing of other members.');
 // Profile opt-in moves members to Crew / Media without granting board roles.
 await api('/api/profile','member',{fullName:'Singer',voiceParts:['alto'],crewMedia:true});
 let crewProfile=(await api('/api/state','member')).profile;assert.equal(crewProfile.isCrew,true);assert.equal(crewProfile.isMedia,false);
 await api('/api/profile','member',{fullName:'Singer',voiceParts:['alto']});assert.equal((await api('/api/state','member')).profile.isCrew,true);
 await api('/api/profile','member',{fullName:'Singer',voiceParts:['alto'],crewMedia:false});assert.equal((await api('/api/state','member')).profile.isCrew,false);
 await api('/api/profile','member',{fullName:'Singer',crewMedia:'yes'},400);
 await api(`/api/members/${member.user.id}/voice-parts`,'md',{voiceParts:['alto'],crewMedia:true});assert.equal((await api('/api/state','member')).profile.isCrew,true);
 await api(`/api/members/${member.user.id}/voice-parts`,'member',{voiceParts:['alto'],crewMedia:false});
 console.log('PASS: self-service Crew / Media opt-in, opt-out, preserved omitted status, delegated editing, and no Media Chair role grant.');
 // Crew is admin-managed, exclusive with Alumni, and visible in member profiles.
 await api(`/api/admin/users/${member.user.id}`,'member',{crew:true},403);
 await api(`/api/admin/users/${member.user.id}`,'md',{crew:true},403);
 let crewState=await api(`/api/admin/users/${member.user.id}`,'admin',{crew:true});
 assert.equal(crewState.members.find(p=>p.id===member.user.id).isCrew,true);
 await api(`/api/admin/users/${member.user.id}`,'admin',{crew:true,alumni:true},400);
 crewState=await api(`/api/admin/users/${member.user.id}`,'admin',{alumni:true});
 assert.equal(crewState.members.find(p=>p.id===member.user.id).isCrew,false);
 assert.equal(crewState.members.find(p=>p.id===member.user.id).isAlumni,true);
 crewState=await api(`/api/admin/users/${member.user.id}`,'admin',{crew:true});
 assert.equal(crewState.members.find(p=>p.id===member.user.id).isAlumni,false);
 await api(`/api/admin/users/${member.user.id}`,'admin',{crew:false});
 await api('/api/phases','member',{title:'Love Yourself',arrangerId:md.user.id},403);
 const round=await api('/api/phases','md',{title:'Love Yourself',arrangerId:md.user.id,votingMode:'feedback'},201);assert.equal(round.phase.title,'Love Yourself');
 const phaseId=round.phase.id;
 await api(`/api/phases/${phaseId}/candidacy`,'member',{join:true});
 await api(`/api/phases/${phaseId}/candidacy`,'md',{join:true});
 await api(`/api/phases/${phaseId}/start`,'md',{});
 await api(`/api/phases/${phaseId}/vote`,'md',{candidateId:member.user.id,reaction:'like'});
 let state=await api('/api/state','md');assert.equal(state.phase.candidates[0].likes,undefined);
 state=await api('/api/state','member');assert.equal(state.phase.candidates[0].likes,undefined);
 await api(`/api/phases/${phaseId}/vote`,'md',{candidateId:member.user.id,reaction:'again'});
 state=await api('/api/state','md');assert.equal(state.phase.candidates.find(c=>c.id===member.user.id).mine,'again');
 await api(`/api/phases/${phaseId}/close`,'member',{},403);
 await api('/api/profile','member',{fullName:'Singer Zhang',voicePart:'Alto',school:'Columbia',gradYear:'2027',funFact:'Loves music'});
 const form=new FormData();form.set('avatar',new Blob([fs.readFileSync('public/icon-192.png')],{type:'image/png'}),'avatar.png');
 const uploadRequest=new Request('https://hub.test/api/profile/avatar',{method:'POST',body:form});
 let r=await mf.dispatchFetch(uploadRequest.url,{method:'POST',headers:{Cookie:cookies.member,'Content-Type':uploadRequest.headers.get('content-type')},body:await uploadRequest.arrayBuffer()});assert.equal(r.status,200,await r.text());
 r=await mf.dispatchFetch(`https://hub.test/api/avatars/${member.user.id}`,{headers:{Cookie:cookies.md}});assert.equal(r.status,200);assert.equal((await r.arrayBuffer()).byteLength,fs.statSync('public/icon-192.png').size);

 // Photo gallery: legacy preservation, cross-member upload, ownership checks, selection and deletion.
 const outsider=await api('/api/register','outsider',{name:'Other singer',password:'abc12345'},201);
 const albumPath='/api/profiles/'+member.user.id+'/photos';
 await api(albumPath,'',undefined,401);
 let album=await api(albumPath,'md');assert.equal(album.photos.length,1);const legacy=album.photos[0];assert.equal(legacy.isAvatar,true);
 async function uploadPhoto(who,bytes=fs.readFileSync('public/icon-192.png'),type='image/png',filename='photo.png',status=201){
  const form=new FormData();form.set('photo',new Blob([bytes],{type}),filename);
  const req=new Request('https://hub.test'+albumPath,{method:'POST',body:form});
  const r=await mf.dispatchFetch(req.url,{method:'POST',headers:{Cookie:cookies[who],'Content-Type':req.headers.get('content-type')},body:await req.arrayBuffer()});
  const body=await r.json();assert.equal(r.status,status,JSON.stringify(body));return body;
 }
 album=await uploadPhoto('md');const added=album.photos.find(p=>p.id!==legacy.id);assert.equal(added.name,'Jingwen');assert.equal(added.canDelete,true);assert.equal(added.canSetAvatar,false);
 await uploadPhoto('md',Buffer.from('not an image'),'image/png','photo.png',400);
 await api('/api/photos/'+added.id+'/avatar','md',{},403);
 await api('/api/photos/'+added.id+'/delete','outsider',{},403);
 await api('/api/photos/'+legacy.id+'/delete','md',{},403);
 await api('/api/photos/'+added.id+'/avatar','member',{});
 album=await api(albumPath,'member');assert.equal(album.photos.find(p=>p.id===added.id).isAvatar,true);assert.equal(album.photos.every(p=>p.canDelete&&p.canSetAvatar),true);
 r=await mf.dispatchFetch('https://hub.test/api/photos/'+added.id,{headers:{Cookie:cookies.outsider}});assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/png');
 await api('/api/photos/'+added.id+'/delete','md',{});
 state=await api('/api/state','member');assert.equal(state.profile.avatar,'');
 album=await api(albumPath,'member');assert.equal(album.photos.length,1);
 await api('/api/photos/'+legacy.id+'/avatar','member',{});
 await api('/api/photos/'+legacy.id+'/delete','member',{});
 album=await api(albumPath,'member');assert.equal(album.photos.length,0);

 await api(`/api/phases/${phaseId}/close`,'md',{});
 state=await api('/api/state','md');assert.equal(state.phase,null);assert.equal(state.history[0].candidates[0].again,undefined);
 await api('/api/google/settings','member',{clientId:'x'},403);
 await api('/api/google/settings','admin',{clientId:'test.apps.googleusercontent.com',clientSecret:'test-secret',spreadsheet:'',parentFolder:''});
 r=await mf.dispatchFetch('https://hub.test/api/google/connect',{headers:{Cookie:cookies.admin},redirect:'manual'});assert.equal(r.status,302);assert.equal(new URL(r.headers.get('location')).searchParams.get('redirect_uri'),'https://hub.test/api/google/callback');
 await api(`/api/phases/${phaseId}/delete`,'admin',{});
 album=await uploadPhoto('md');const cleanupPhoto=album.photos[0];
 await api(`/api/admin/users/${member.user.id}/delete`,'admin',{});
 await api('/api/photos/'+cleanupPhoto.id,'md',undefined,404);
 const photoFiles=await mf.getR2Bucket('FILES');assert.equal(await photoFiles.get('photos/'+cleanupPhoto.id+'.png'),null);
 state=await api('/api/state','md');assert.equal(state.members.some(x=>x.id===member.user.id),false);
 await api('/api/register','blocked',{name:'Uninvited',password:'abc12345'},403);
 await api('/api/admin/invitations','md',{},403);
 const invite=await api('/api/admin/invitations','admin',{},201);
 await api('/api/register','invited',{name:'Invited',password:'abc12345',invitationCode:invite.code},201);
 await api('/api/register','reused',{name:'Reused',password:'abc12345',invitationCode:invite.code},201);
 assert.equal((await query('SELECT use_count FROM cucac.invitations WHERE id=$1',[invite.id])).rows[0].use_count,2);
 const single=await api('/api/admin/invitations','admin',{},201);
 await query('UPDATE cucac.invitations SET is_shared=0 WHERE id=$1',[single.id]);
 await api('/api/register','single',{name:'Single',password:'abc12345',invitationCode:single.code},201);
 await api('/api/register','single2',{name:'Single2',password:'abc12345',invitationCode:single.code},403);
 const revoked=await api('/api/admin/invitations','admin',{},201);
 await api('/api/admin/invitations/'+revoked.id+'/revoke','admin',{});
 await api('/api/register','revoked',{name:'Revoked',password:'abc12345',invitationCode:revoked.code},403);
 const expired=await api('/api/admin/invitations','admin',{},201);
 await query('UPDATE cucac.invitations SET expires_at=$1 WHERE id=$2',['2000-01-01',expired.id]);
 await api('/api/register','expired',{name:'Expired',password:'abc12345',invitationCode:expired.code},403);
 const reusable=await api('/api/admin/invitations','admin',{},201);
 await assert.rejects(env.invitations.register({code:reusable.code,name:'Jingwen',passwordHash:'test',createdAt:new Date().toISOString()}),e=>e.message==='name_taken');
 await api('/api/register','retry',{name:'Retry',password:'abc12345',invitationCode:reusable.code},201);
 await api('/api/login','case',{name:'jINGWEN',password:'abc12345'});
 await assert.rejects(env.DB.batch([env.DB.prepare('INSERT INTO arrangers(name,created_at) VALUES(?,?)').bind('Rollback probe','now'),env.DB.prepare('INSERT INTO arrangers(name,created_at) VALUES(?,?)').bind('Rollback probe','now')]));
 assert.equal((await query("SELECT * FROM cucac.arrangers WHERE name='Rollback probe'")).rows.length,0);
 assert.equal((await query("SELECT count(*)::int AS n FROM pg_tables WHERE schemaname='cucac' AND rowsecurity")).rows[0].n,13);

 // Default voting: preparation, two-candidate lock, cancellation, and server-side limits.
 let v=await api('/api/phases','md',{title:'Two singers',arrangerId:md.user.id},201);
 let vid=v.phase.id;assert.equal(v.phase.votingMode,'default');assert.equal(v.phase.started,false);
 await api(`/api/phases/${vid}/candidacy`,'md',{join:true});
 await api(`/api/phases/${vid}/candidacy`,'outsider',{join:true});
 await api(`/api/phases/${vid}/vote`,'md',{candidateId:md.user.id,reaction:'like'},403);
 await api(`/api/phases/${vid}/start`,'outsider',{},403);
 v=await api(`/api/phases/${vid}/start`,'md',{});assert.equal(v.phase.registrationLocked,true);
 await api(`/api/phases/${vid}/candidacy`,'retry',{join:true},403);
 await api(`/api/phases/${vid}/vote`,'retry',{candidateId:md.user.id,reaction:'like'});
 await api(`/api/phases/${vid}/vote`,'retry',{candidateId:outsider.user.id,reaction:'like'},400);
 await api(`/api/phases/${vid}/vote`,'retry',{candidateId:md.user.id,reaction:null});
 await api(`/api/phases/${vid}/vote`,'retry',{candidateId:outsider.user.id,reaction:'like'});
 await api(`/api/phases/${vid}/vote`,'retry',{candidateId:md.user.id,reaction:'again'},400);
 await api(`/api/phases/${vid}/close`,'md',{});
 // Five singers: initial random order persists and late registrations append.
 v=await api('/api/phases','md',{title:'Shared ranks',arrangerId:md.user.id},201);vid=v.phase.id;
 for(const who of ['md','outsider','retry'])await api(`/api/phases/${vid}/candidacy`,who,{join:true});
 v=await api(`/api/phases/${vid}/start`,'md',{});const order=v.phase.candidates.map(c=>c.id);
 assert.deepEqual([...order].sort((a,b)=>a-b),[md.user.id,outsider.user.id,(await api('/api/state','retry')).user.id].sort((a,b)=>a-b));
 assert.deepEqual((await api('/api/state','md')).phase.candidates.map(c=>c.id),order);
 v=await api(`/api/phases/${vid}/candidacy`,'invited',{join:true});const fourth=v.user.id;
 assert.deepEqual(v.phase.candidates.slice(0,3).map(c=>c.id),order);assert.equal(v.phase.candidates.at(-1).id,fourth);
 v=await api(`/api/phases/${vid}/candidacy`,'single',{join:true});const fifth=v.user.id;
 const ids=v.phase.candidates.map(c=>c.id);
 await api(`/api/phases/${vid}/vote`,'md',{candidateId:ids[0],reaction:'like'});
 await api(`/api/phases/${vid}/vote`,'md',{candidateId:ids[1],reaction:'like'});
 await api(`/api/phases/${vid}/vote`,'md',{candidateId:ids[2],reaction:'like'},400);
 // Fixture for two ties at each of ranks 1 and 2, plus one lower rank.
 await query('DELETE FROM cucac.votes WHERE phase_id=$1',[vid]);
 const voterIds=(await query('SELECT id FROM cucac.users ORDER BY id')).rows.map(r=>r.id);
 for(let ci=0;ci<5;ci++)for(let j=0;j<[3,3,2,2,1][ci];j++)await query('INSERT INTO cucac.votes(phase_id,voter_id,candidate_id,reaction) VALUES($1,$2,$3,$4)',[vid,voterIds[j],ids[ci],'like']);
 v=await api(`/api/phases/${vid}/close`,'md',{});
 let results=v.history.find(r=>r.id===vid);assert.equal(results.candidates.length,4);assert.deepEqual(results.candidates.map(c=>c.rank),[1,1,2,2]);
 for(const c of results.candidates){assert.equal(c.likes,undefined);assert.equal(c.again,undefined);assert.equal(c.mine,undefined);}
 let adminResults=(await api('/api/state','admin')).history.find(r=>r.id===vid);assert.equal(adminResults.candidates.length,5);assert.deepEqual(adminResults.candidates.map(c=>c.likes),[3,3,2,2,1]);
 assert.equal(adminResults.canSeeResults,true);assert.equal(adminResults.canReveal,false);
 assert.equal(adminResults.candidates.at(-1).rank,3);assert.equal(adminResults.candidates.at(-1).likes,1);
 assert.equal(results.canReveal,true);
 await api(`/api/phases/${vid}/reveal`,'admin',{},403);
 assert.equal((await api('/api/state','admin')).history.find(r=>r.id===vid).revealedRanks,2);
 assert.equal((await api('/api/state','outsider')).history.find(r=>r.id===vid).candidates.length,4);
 await api(`/api/phases/${vid}/reveal`,'outsider',{},403);
 await api(`/api/phases/${vid}/reveal`,'md',{});
 results=(await api('/api/state','outsider')).history.find(r=>r.id===vid);assert.equal(results.candidates.length,5);assert.equal(results.candidates.at(-1).rank,3);assert.equal(results.candidates.at(-1).likes,undefined);
 // Duet pair voting: invitations require the other member's confirmation.
 let duet=await api('/api/phases','md',{title:'Two pairs',arrangerId:md.user.id,pollType:'pair'},201);
 let did=duet.phase.id;
 const users={md:md.user.id,outsider:outsider.user.id,retry:(await api('/api/state','retry')).user.id,invited:(await api('/api/state','invited')).user.id,single:(await api('/api/state','single')).user.id};
 await api(`/api/phases/${did}/pair`,'md',{partnerId:users.md},400);
 await api(`/api/phases/${did}/pair`,'md',{partnerId:users.outsider,auditionUrl:'javascript:alert(1)'},400);
 duet=await api(`/api/phases/${did}/pair`,'md',{partnerId:users.outsider,auditionUrl:'https://drive.google.com/test'});
 assert.equal(duet.phase.candidates.length,0);assert.equal(duet.phase.pendingPairs.length,1);
 assert.equal((await api('/api/state','retry')).phase.pendingPairs.length,0);
 const first=duet.phase.pendingPairs[0].id;
 await api(`/api/phases/${did}/pair`,'outsider',{partnerId:users.md},409);
 await api(`/api/phases/${did}/confirm`,'md',{entryId:first},403);
 await api(`/api/phases/${did}/confirm`,'retry',{entryId:first},403);
 duet=await api(`/api/phases/${did}/confirm`,'outsider',{entryId:first});assert.equal(duet.phase.candidates.length,1);
 await api(`/api/phases/${did}/start`,'md',{},400);
 duet=await api(`/api/phases/${did}/pair`,'retry',{partnerId:users.invited});const second=duet.phase.pendingPairs[0].id;
 await api(`/api/phases/${did}/confirm`,'invited',{entryId:second});
 duet=await api(`/api/phases/${did}/pair`,'single',{partnerId:users.md});const pending=duet.phase.pendingPairs[0].id;
 duet=await api(`/api/phases/${did}/start`,'md',{});assert.equal(duet.phase.registrationLocked,true);
 await api(`/api/phases/${did}/confirm`,'md',{entryId:pending},403);
 await api(`/api/phases/${did}/vote`,'single',{entryId:pending,reaction:'like'},400);
 await api(`/api/phases/${did}/pair`,'single',{partnerId:users.invited},403);
 await api(`/api/phases/${did}/vote`,'md',{entryId:first,reaction:'like'});
 await api(`/api/phases/${did}/vote`,'md',{entryId:second,reaction:'like'},400);
 await api(`/api/phases/${did}/vote`,'md',{entryId:first,reaction:null});
 duet=await api(`/api/phases/${did}/vote`,'md',{entryId:second,reaction:'like'});assert.equal(duet.phase.candidates.find(e=>e.id===second).mine,'like');
 assert.equal(duet.phase.candidates.find(e=>e.id===second).likes,undefined);
 await api(`/api/phases/${did}/cancel`,'md',{entryId:first},403);
 await api(`/api/phases/${did}/audition`,'retry',{entryId:first,auditionUrl:'https://example.org'},403);
 await api(`/api/phases/${did}/close`,'md',{});
 let duoHistory=(await api('/api/state','md')).history.find(h=>h.id===did);assert.equal(duoHistory.pollType,'pair');assert.equal(duoHistory.candidates.every(e=>e.likes===undefined&&e.mine===undefined),true);
 assert.equal((await api('/api/state','admin')).history.find(h=>h.id===did).candidates[0].likes,1);
 await api(`/api/phases/${did}/reveal`,'admin',{},403);
 await api(`/api/phases/${did}/audition`,'md',{entryId:first,auditionUrl:'https://example.org'},400);

 // Three-pair ballots permit two choices and append later confirmed pairs.
 duet=await api('/api/phases','md',{title:'Open pairs',arrangerId:md.user.id,pollType:'pair'},201);did=duet.phase.id;
 const pairs=[];
 for(const partner of ['outsider','retry','invited']){duet=await api(`/api/phases/${did}/pair`,'md',{partnerId:users[partner]});const entry=duet.phase.pendingPairs.find(e=>e.members.some(m=>m.id===users[partner]));pairs.push(entry.id);await api(`/api/phases/${did}/confirm`,partner,{entryId:entry.id});}
 duet=await api(`/api/phases/${did}/start`,'md',{});const pairOrder=duet.phase.candidates.map(e=>e.id);assert.equal(duet.phase.registrationLocked,false);
 await api(`/api/phases/${did}/vote`,'single',{entryId:pairs[0],reaction:'like'});
 await api(`/api/phases/${did}/vote`,'single',{entryId:pairs[1],reaction:'like'});
 await api(`/api/phases/${did}/vote`,'single',{entryId:pairs[2],reaction:'like'},400);
 duet=await api(`/api/phases/${did}/pair`,'single',{partnerId:users.md});const late=duet.phase.pendingPairs[0].id;
 duet=await api(`/api/phases/${did}/confirm`,'md',{entryId:late});assert.deepEqual(duet.phase.candidates.slice(0,3).map(e=>e.id),pairOrder);assert.equal(duet.phase.candidates.at(-1).id,late);
 await api(`/api/phases/${did}/cancel`,'single',{entryId:late});
 await api(`/api/phases/${did}/cancel`,'md',{entryId:pairs[0]},403);
 await api(`/api/phases/${did}/close`,'md',{});

 // Independent part ballots, custom labels, one-part registration and per-part ties.
 const extra=await api('/api/register','sixth',{name:'Duet sixth',password:'abc12345'},201);users.sixth=extra.user.id;
 duet=await api('/api/phases','md',{title:'Part voting',arrangerId:md.user.id,pollType:'parts',partA:'High voice',partB:'Low voice'},201);did=duet.phase.id;
 assert.equal(duet.phase.partA,'High voice');assert.equal(duet.phase.partB,'Low voice');
 await api(`/api/phases/${did}/candidacy`,'md',{join:true,part:'A'});
 await api(`/api/phases/${did}/start`,'md',{},400);
 await api(`/api/phases/${did}/candidacy`,'md',{join:true,part:'B'},409);
 for(const who of ['outsider','retry'])await api(`/api/phases/${did}/candidacy`,who,{join:true,part:'A'});
 for(const who of ['invited','single','sixth'])await api(`/api/phases/${did}/candidacy`,who,{join:true,part:'B'});
 duet=await api(`/api/phases/${did}/start`,'md',{});
 assert.deepEqual(duet.phase.voteLimits,{A:2,B:2});assert.deepEqual(duet.phase.partLocks,{A:false,B:false});
 const aEntries=duet.phase.candidates.filter(e=>e.part==='A'),bEntries=duet.phase.candidates.filter(e=>e.part==='B');
 for(const entry of [...aEntries.slice(0,2),...bEntries.slice(0,2)])await api(`/api/phases/${did}/vote`,'md',{entryId:entry.id,reaction:'like'});
 await api(`/api/phases/${did}/vote`,'md',{entryId:aEntries[2].id,reaction:'like'},400);
 await api(`/api/phases/${did}/vote`,'md',{entryId:bEntries[2].id,reaction:'like'},400);
 await api(`/api/phases/${did}/cancel`,'md',{entryId:aEntries.find(e=>e.isMe).id},403);
 await query('DELETE FROM cucac.duet_votes WHERE phase_id=$1',[did]);
 for(const entries of [aEntries,bEntries])for(let i=0;i<3;i++)for(let j=0;j<(entries===bEntries?[3,2,2]:[3,2,1])[i];j++)await query('INSERT INTO cucac.duet_votes(phase_id,entry_id,voter_id) VALUES($1,$2,$3)',[did,entries[i].id,voterIds[j]]);
 await api(`/api/phases/${did}/close`,'md',{});
 duoHistory=(await api('/api/state','single')).history.find(h=>h.id===did);assert.deepEqual(duoHistory.candidates.map(e=>e.rank),[1,2,1,2,2]);assert.equal(duoHistory.candidates.every(e=>e.likes===undefined&&e.mine===undefined),true);
 assert.equal((await api('/api/state','admin')).history.find(h=>h.id===did).candidates.length,6);
 await api(`/api/phases/${did}/reveal`,'admin',{},403);
 await api(`/api/phases/${did}/reveal`,'md',{});
 assert.deepEqual((await api('/api/state','single')).history.find(h=>h.id===did).candidates.map(e=>e.rank),[1,2,3,1,2,2]);
 await api(`/api/phases/${did}/delete`,'admin',{});
 assert.equal((await query('SELECT count(*)::int AS n FROM cucac.duet_entries WHERE phase_id=$1',[did])).rows[0].n,0);
 assert.equal((await query('SELECT count(*)::int AS n FROM cucac.duet_votes WHERE phase_id=$1',[did])).rows[0].n,0);

 duet=await api('/api/phases','md',{title:'Small parts',arrangerId:md.user.id,pollType:'parts'},201);did=duet.phase.id;
 for(const who of ['md','outsider'])await api(`/api/phases/${did}/candidacy`,who,{join:true,part:'A'});
 await api(`/api/phases/${did}/candidacy`,'single',{join:true,part:'B'});
 duet=await api(`/api/phases/${did}/start`,'md',{});assert.deepEqual(duet.phase.voteLimits,{A:1,B:1});
 await api(`/api/phases/${did}/candidacy`,'sixth',{join:true,part:'A'},403);
 await api(`/api/phases/${did}/candidacy`,'sixth',{join:true,part:'B'},403);
 const smallA=duet.phase.candidates.filter(e=>e.part==='A');
 await api(`/api/phases/${did}/vote`,'sixth',{entryId:smallA[0].id,reaction:'like'});
 await api(`/api/phases/${did}/vote`,'sixth',{entryId:smallA[1].id,reaction:'like'},400);
 await api(`/api/phases/${did}/vote`,'sixth',{entryId:duet.phase.candidates.find(e=>e.part==='B').id,reaction:'like'});
 // Private recording upload authorization, playback and one-week expiration.
 const audioEntry=duet.phase.candidates.find(e=>e.members.some(m=>m.id===users.md));
 await api(`/api/phases/${did}/recordings`,'',{entryId:audioEntry.id,mime:'audio/webm',size:10},401);
 await api(`/api/phases/${did}/recordings`,'sixth',{entryId:audioEntry.id,mime:'audio/webm',size:10},403);
 await api(`/api/phases/${did}/recordings`,'md',{entryId:audioEntry.id,mime:'text/html',size:10},400);
 await api(`/api/phases/${did}/recordings`,'md',{entryId:audioEntry.id,mime:'audio/webm',size:51*1024*1024},413);
 async function putAudio(who,phaseId,target){const upload=await api(`/api/phases/${phaseId}/recordings`,who,{...target,mime:'audio/webm',size:10},201);const key=(await query('SELECT object_key FROM cucac.recordings WHERE id=$1',[upload.id])).rows[0].object_key;files.set(key,Buffer.from('audio data'));await api(`/api/recordings/${upload.id}/complete`,who,{});return {...upload,key};}
 const clip=await putAudio('md',did,{entryId:audioEntry.id});
 let audioState=await api('/api/state','sixth');assert.equal(audioState.phase.recordings.length,1);assert.equal(audioState.phase.recordings[0].canDelete,false);
 await api(`/api/recordings/${clip.id}/delete`,'sixth',{},403);
 r=await mf.dispatchFetch(`https://hub.test/api/recordings/${clip.id}`);assert.equal(r.status,401);
 r=await mf.dispatchFetch(`https://hub.test/api/recordings/${clip.id}`,{headers:{Cookie:cookies.sixth}});assert.equal(r.status,302);assert.match(r.headers.get('location'),/^https:\/\/storage.test\/play\//);
 await query("UPDATE cucac.recordings SET created_at=now()-interval '30 days' WHERE id=$1",[clip.id]);
 await env.recordings.cleanup();assert.equal(files.has(clip.key),true); // Open voting retains recordings regardless of creation age.
 await api(`/api/phases/${did}/close`,'md',{});
 audioState=await api('/api/state','sixth');assert.equal(audioState.history.find(h=>h.id===did).recordings.length,1);
 await query("UPDATE cucac.phases SET closed_at=(now()-interval '8 days')::text WHERE id=$1",[did]);
 r=await mf.dispatchFetch(`https://hub.test/api/recordings/${clip.id}`,{headers:{Cookie:cookies.sixth}});assert.equal(r.status,410);
 assert.equal((await api('/api/state','sixth')).history.find(h=>h.id===did).recordings.length,0);
 await env.recordings.cleanup();assert.equal(files.has(clip.key),false);assert.equal((await query('SELECT 1 FROM cucac.recordings WHERE id=$1',[clip.id])).rows.length,0);
 // Either confirmed partner can delete a pair's recording, but only the uploader can finalize an upload.
 duet=await api('/api/phases','md',{title:'Pair recording',arrangerId:md.user.id,pollType:'pair'},201);did=duet.phase.id;
 duet=await api(`/api/phases/${did}/pair`,'md',{partnerId:users.outsider});const audioPair=duet.phase.pendingPairs[0].id;
 await api(`/api/phases/${did}/recordings`,'md',{entryId:audioPair,mime:'audio/webm',size:10},403);
 await api(`/api/phases/${did}/confirm`,'outsider',{entryId:audioPair});
 const pairedClip=await putAudio('outsider',did,{entryId:audioPair});
 await api(`/api/recordings/${pairedClip.id}/complete`,'md',{},403);
 await api(`/api/recordings/${pairedClip.id}/delete`,'md',{});assert.equal(files.has(pairedClip.key),false);
 await api(`/api/phases/${did}/close`,'md',{});
 duet=await api('/api/phases','md',{title:'Solo recording',arrangerId:md.user.id},201);did=duet.phase.id;
 await api(`/api/phases/${did}/recordings`,'md',{candidateId:users.md,mime:'audio/webm',size:10},400);
 await api(`/api/phases/${did}/candidacy`,'md',{join:true});
 const soloClip=await putAudio('md',did,{candidateId:users.md});
 await api(`/api/phases/${did}/recordings`,'single',{candidateId:users.md,mime:'audio/webm',size:10},403);
 await api(`/api/phases/${did}/candidacy`,'md',{join:false});assert.equal((await api('/api/state','md')).phase.recordings.length,0);
 await query("UPDATE cucac.recordings SET created_at=now()-interval '2 days' WHERE id=$1",[soloClip.id]);await env.recordings.cleanup();assert.equal(files.has(soloClip.key),false);
 console.log('PASS: recording ownership, signed upload flow, confirmed-pair sharing, authenticated playback, no creation-age limit in open rounds, exact post-close expiry, private history recordings, and storage cleanup.');

 console.log('PASS: pair confirmation, invitation ownership, shared singers, locked two-pair ballot, two-choice pair ballot, late confirmation order, per-part limits/ranks/privacy, MD reveal, audition URL validation and cascade cleanup.');

 console.log('PASS: default voting limits, start permissions, locked two-singer registration, persistent shuffled order, late appends, dense ties, admin-only counts, MD reveal, and private result API.');
 console.log('PASS: PostgreSQL adapter, invite-required registration, single-use/expiry/revocation/rollback, case-insensitive login, private schema; Worker runtime, registration/login, roles, shared votes, result visibility, profile/avatar, gallery permissions and cleanup, history, deletion, Google redirect/config.');
} finally {await mf.dispose();}
