import fs from 'node:fs';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
const state=JSON.parse(fs.readFileSync(process.argv[2]||'/tmp/plan-state.json','utf8'));
state.phase=null;state.user.isMd=true;state.admin={rounds:[{id:777,title:'Past Solo',status:'closed',pollType:'solo',openedBy:'MD',planSongId:1,planSongTitle:'江南'}]};
const people=state.members.filter(m=>!m.isAlumni&&!m.isCrew).map(m=>({id:m.id,name:m.fullName||m.name,voiceParts:m.voiceParts}));
state.library={...(state.library||{}),ready:true,semesters:[{id:10,label:'2026 Fall'},{id:11,label:'2025 Fall'}]};
const data={terms:[{id:1,label:'2026 Fall',is_current:true,archived:false},{id:2,label:'2025 Fall',is_current:false,archived:true}],term:{id:1,label:'2026 Fall',isCurrent:true,archived:false},canManage:true,canChoose:true,members:people,songs:[{id:1,title:'江南',folderUrl:'https://drive.google.com/drive/folders/song1',locked:false,entries:[]},{id:2,title:'天黑黑',folderUrl:'',locked:true,entries:[]}]};
const calls=[],window=new Window({url:'http://localhost/',settings:{disableJavaScriptFileLoading:true,disableCSSFileLoading:true,enableJavaScriptEvaluation:true,suppressInsecureJavaScriptEnvironmentWarning:true}});
try{
 window.document.write(fs.readFileSync('public/index.html','utf8').replace(/<script[\s\S]*?<\/script>/g,''));
 window.fetch=async(url,options={})=>{const parsed=new URL(url,'http://localhost'),path=parsed.pathname;let result={};if(path==='/api/state')result=state;
 else if(path==='/api/plan/library'){calls.push({path,source:parsed.searchParams.get('semesterId')});result={folders:parsed.searchParams.has('semesterId')?[{name:'Older song',id:'song4',semester:'2025 Fall'}]:[{name:'Love Yourself',id:'song3',semester:'2026 Fall'},{name:'Older song',id:'song4',semester:'2025 Fall'}]};}
 else if(path==='/api/plan'){result=data;}
 else if(path.startsWith('/api/plan/')){const body=JSON.parse(options.body);calls.push({path,body});const id=Number(path.split('/').at(-1));
  if(path.includes('/entry/')){const memberId=body.memberId||window.planTest.user().id,song=data.songs.find(s=>s.id===id);if(body.remove)song.entries=song.entries.filter(e=>!(e.memberId===memberId&&e.part===body.part));else if(!song.entries.some(e=>e.memberId===memberId&&e.part===body.part))song.entries.push({memberId,name:people.find(p=>p.id===memberId)?.name||'Singer',part:body.part});}
  if(path.includes('/save/'))data.songs=structuredClone(window.planTest.data().songs);
  if(path.includes('/lock/'))data.songs.find(s=>s.id===id).locked=body.locked;
  if(path.includes('/big/'))data.songs.find(s=>s.id===id).bigSong=body.bigSong;
  if(path.includes('/add/'))data.songs.push({id:3,title:body.title,folderUrl:'',locked:false,entries:[]});result=data;}
 return {ok:true,json:async()=>structuredClone(result)};};
 const html=fs.readFileSync('public/index.html','utf8'),main=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('const loading'))[1];
 window.eval(fs.readFileSync('public/plan.js','utf8')+'\n'+main+'\nwindow.planTest={data:()=>planData,name:planMemberName,user:()=>latest.user,open:planOpenSong,rerender:()=>render(latest),member:()=>{latest.user={id:'+people[0].id+',isAdmin:false,isMd:false};latest.profile={isAlumni:false,isCrew:false,voiceParts:["alto"]};planData.canManage=false;planData.canChoose=false;renderPlan();},archive:()=>{planData.term.archived=true;renderPlan();}};');
 assert.equal(window.planTest.name({fullName:'Jingwen Zhang',name:'login67'}),'Jingwen');assert.equal(window.planTest.name({fullName:'',name:'login67'}),'login67');
 const tick=()=>new Promise(resolve=>setTimeout(resolve,0));await tick();await tick();const doc=window.document;
 doc.querySelector('#open-poll').click();await tick();await tick();const pollSong=doc.querySelector('select[name="planSongId"]');assert.ok(pollSong);assert.ok([...pollSong.options].some(o=>o.textContent.includes('江南')));assert.ok(pollSong.closest('label').compareDocumentPosition(doc.querySelector('#round input[name="title"]').closest('label'))&window.Node.DOCUMENT_POSITION_FOLLOWING);const pollName=doc.querySelector('#round input[name="title"]');assert.ok(!pollName.placeholder);pollName.value='Round 2';pollSong.value='1';pollSong.dispatchEvent(new window.Event('change'));assert.equal(doc.querySelector('#round .poll-title-prefix').textContent,'江南-');assert.equal(pollName.value,'Round 2');doc.querySelector('#poll-back').click();
 const manageRow=doc.querySelector('#admin .person-row');assert.ok(manageRow);const manageButtons=manageRow.querySelectorAll('button');assert.equal(manageButtons.length,2);assert.ok(manageButtons[0].classList.contains('nav-btn'));assert.ok(manageButtons[1].classList.contains('nav-btn'));assert.ok(manageButtons[0].parentElement.classList.contains('round-manage-actions'));assert.ok(manageButtons[0].textContent.includes('Edit'));assert.equal(manageButtons[0].parentElement,manageButtons[1].parentElement);manageButtons[1].click();assert.equal(manageRow.nextElementSibling.hidden,false);manageRow.nextElementSibling.querySelectorAll('button')[1].click();assert.equal(manageRow.nextElementSibling.hidden,true);
 assert.ok(doc.querySelector('#open-plan').textContent.includes('这学期唱什么'));assert.equal(doc.querySelector('#browse-lineup'),null);
 doc.querySelector('#open-plan').click();await tick();await tick();const body=doc.querySelector('#plan-body');assert.doesNotMatch(body.textContent,/null/);assert.ok(body.textContent.includes('Current semester PDF check'));
 assert.deepEqual([...doc.querySelectorAll('.plan-table thead th')].slice(1).map(n=>n.textContent),['Solo','Soprano','Alto','Tenor','Baritone','Bass','Bbox']);
 assert.equal(doc.querySelector('.plan-table tbody tr th .plan-song-title').textContent,'江南');assert.equal(doc.querySelector('.plan-table tbody tr th a').href,'http://localhost/pdf.html?folderId=song1');assert.equal(doc.querySelectorAll('.plan-table tbody tr th a')[1].href,'https://drive.google.com/drive/folders/song1');
 assert.equal(doc.querySelectorAll('.plan-cell-add').length,0);assert.equal(doc.querySelectorAll('.plan-table th input[type="checkbox"]').length,0);
 doc.querySelector('#plan-edit-toggle').click();assert.ok(doc.querySelectorAll('.plan-cell-add').length>0);
 const beforeCalls=calls.length;const big=doc.querySelector('tr[data-song-id="1"] th input');big.checked=true;big.dispatchEvent(new window.Event('change'));await tick();assert.equal(calls.length,beforeCalls);assert.ok(doc.querySelector('tr[data-song-id="1"] th input').checked);
 const reopen=doc.querySelector('tr[data-song-id="1"] th input');reopen.checked=false;reopen.dispatchEvent(new window.Event('change'));await tick();
 const soloForm=doc.querySelector('tr[data-song-id="1"] td[data-part="solo"] form');soloForm.elements.memberId.value=String(people[0].id);soloForm.dispatchEvent(new window.Event('submit',{cancelable:true}));await tick();assert.equal(calls.length,beforeCalls);
 const otherBig=doc.querySelector('tr[data-song-id="2"] th input');otherBig.checked=true;otherBig.dispatchEvent(new window.Event('change'));
 doc.querySelector('#plan-edit-toggle').click();await tick();await tick();assert.equal(calls.at(-1).path,'/api/plan/save/1');assert.equal(calls.at(-1).body.changes.length,4);assert.equal(doc.querySelectorAll('.plan-big-song-tag').length,1);assert.ok(doc.querySelector('tr[data-song-id="2"] .plan-big-song-tag'));assert.equal(doc.querySelectorAll('.plan-table th input').length,0);assert.doesNotMatch(doc.querySelector('.plan-table').textContent,/↗/);assert.equal(doc.querySelectorAll('.plan-cell-add').length,0);assert.equal(doc.querySelectorAll('.plan-table th input[type="checkbox"]').length,0);
 doc.querySelector('#plan-edit-toggle').click();
 [...doc.querySelectorAll('#plan button')].find(b=>b.textContent.includes('Add / manage songs')).click();await tick();await tick();assert.equal(doc.querySelectorAll('.plan-library-choice').length,2);
 const source=doc.querySelector('#plan select[aria-label="曲库学期 / Library semester"]');source.value='11';source.dispatchEvent(new window.Event('change'));await tick();await tick();assert.equal(calls.at(-1).source,'11');assert.equal(doc.querySelectorAll('.plan-library-choice').length,1);
 const search=doc.querySelector('#plan input[aria-label="搜索曲库 / Search score library"]');search.value='Older';search.dispatchEvent(new window.Event('input'));const choice=doc.querySelector('.plan-library-choice input');choice.checked=true;choice.dispatchEvent(new window.Event('change'));
 [...doc.querySelectorAll('#plan button')].find(b=>b.textContent.includes('Add selected songs')).click();await tick();await tick();assert.equal(calls.at(-1).body.songs[0].folderUrl,'https://drive.google.com/drive/folders/song4');
 const manual=doc.querySelector('#plan form input[name="title"]');manual.value='Unwritten score';manual.focus();window.planTest.rerender();assert.equal(doc.querySelector('#plan form input[name="title"]').value,'Unwritten score');manual.closest('form').dispatchEvent(new window.Event('submit',{cancelable:true}));await tick();await tick();assert.equal(calls.at(-1).path,'/api/plan/add/1');
 [...doc.querySelectorAll('#plan button')].find(b=>b.textContent.includes('Back to lineup')).click();assert.ok(doc.querySelector('.plan-table').textContent.includes('Scores pending'));
 data.canManage=false;data.canChoose=false;window.planTest.member();assert.ok(!body.textContent.includes('Current semester PDF check'));assert.equal(doc.querySelectorAll('.plan-table th input[type="checkbox"]').length,0);assert.equal(doc.querySelector('td[data-part="solo"] .plan-join'),null);assert.equal(doc.querySelectorAll('.plan-cell-add').length,0);
 doc.querySelector('tr[data-song-id="1"] td[data-part="bass"] .plan-join').click();await tick();await tick();assert.equal(calls.at(-1).body.part,'bass');
 doc.querySelector('tr[data-song-id="1"] td[data-part="tenor"] .plan-join').click();await tick();await tick();assert.ok(doc.querySelector('tr[data-song-id="1"] td[data-part="bass"] .plan-name'));assert.ok(doc.querySelector('tr[data-song-id="1"] td[data-part="tenor"] .plan-name'));
 doc.querySelector('tr[data-song-id="1"] td[data-part="bass"] .plan-remove').click();await tick();await tick();assert.equal(calls.at(-1).body.remove,true);assert.ok(doc.querySelector('tr[data-song-id="1"] td[data-part="tenor"] .plan-name'));assert.ok(!doc.querySelector('td[data-part="solo"] .plan-remove'));
 window.planTest.archive();assert.equal(doc.querySelectorAll('.plan-join,.plan-remove,.plan-cell-add').length,0);assert.doesNotMatch(body.textContent,/null/);
 console.log('PASS: independent bilingual entry, song/part roster orientation, Solo assignment, physical-semester library filtering, bulk checkbox selection, manual pending-score titles, cross-part multi-signup, isolated removal, draft preservation and archived read-only display.');
}finally{await window.happyDOM.abort();window.close();}
