import fs from 'node:fs';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
const window=new Window({url:'https://hub.test/pdf.html?folderId=scoreFolder123',settings:{disableJavaScriptFileLoading:true,disableCSSFileLoading:true,enableJavaScriptEvaluation:true,suppressInsecureJavaScriptEnvironmentWarning:true}});
const calls=[],renders=[];let pausedRender=null;let selected='firstPdfFile123';const files=[{id:selected,name:'first.pdf'},{id:'latestPdfFile123',name:'latest.pdf'}];
window.happyDOM.setWindowSize({width:390,height:844});
try{window.document.write(fs.readFileSync('public/pdf.html','utf8').replace(/<script[\s\S]*?<\/script>/g,''));window.HTMLCanvasElement.prototype.getContext=()=>({drawImage(){}});window.pdfTestLib={GlobalWorkerOptions:{},getDocument:()=>({destroy:async()=>{},promise:Promise.resolve({numPages:3,destroy:async()=>{},getPage:async page=>({getViewport:({scale})=>({width:600*scale,height:800*scale}),render:()=>{renders.push(page);return {promise:pausedRender||Promise.resolve(),cancel(){}};}})})})};window.fetch=async(input,options={})=>{const url=new URL(input,'https://hub.test');calls.push({path:url.pathname,fileId:url.searchParams.get('fileId'),method:options.method||'GET'});let data;if(url.pathname.endsWith('info'))data={files,defaultPdfId:selected,canManagePdf:true,canManagePdfPanel:false};else if(url.pathname.endsWith('star')){selected=JSON.parse(options.body).fileId;data={files,defaultPdfId:selected,selection:'starred'};}else if(url.pathname.endsWith('url'))data={url:'https://private.test/read.pdf',name:files.find(f=>f.id===url.searchParams.get('fileId')).name,fileId:url.searchParams.get('fileId')};else return {ok:true,blob:async()=>new window.Blob(['PDF'])};return {ok:true,json:async()=>data};};window.URL.createObjectURL=()=> 'blob:test';window.URL.revokeObjectURL=()=>{};window.HTMLAnchorElement.prototype.click=function(){this.clicked=true;};window.eval(fs.readFileSync('public/pdf-viewer.mjs','utf8').replace("await import('/pdfjs.mjs')",'window.pdfTestLib'));
const tick=async()=>{for(let i=0;i<8;i++)await new Promise(resolve=>setTimeout(resolve,0));};await tick();const $=id=>window.document.getElementById(id);
assert.equal($('manage').hidden,true);assert.equal($('file').value,selected);assert.equal($('canvas').hidden,false);assert.equal($('download').disabled,false);assert.equal($('fullscreen').disabled,false);assert.equal($('count').textContent,'/ 3');assert.equal($('fit').tagName,'BUTTON');assert.equal($('read-direction').tagName,'BUTTON');assert.equal(parseFloat($('canvas').style.width),window.innerWidth);assert.deepEqual(renders,[1]);assert.ok(!calls.some(c=>c.path==='/read.pdf'));
$('larger').click();await tick();assert.notEqual(parseFloat($('canvas').style.width),window.innerWidth);$('fit').click();await tick();assert.equal(parseFloat($('canvas').style.width),window.innerWidth);
let releasePage;pausedRender=new Promise(resolve=>{releasePage=resolve;});const oldWidth=$('canvas').width;$('next').click();await tick();assert.equal($('canvas').width,oldWidth,'old paper remains intact during background rendering');assert.ok($('page-frame').querySelector('.outgoing-page'));assert.ok(!$('page-frame').classList.contains('slide-next'),'slide waits for complete PDF rendering');pausedRender=null;releasePage();await tick();assert.ok($('page-frame').classList.contains('slide-next'));assert.match(window.getComputedStyle($('page-frame')).backgroundColor,/white|#fff|rgb\(255, 255, 255\)/);assert.ok(!/opacity/.test(fs.readFileSync('public/pdf.html','utf8').match(/@keyframes paper-in-next[^@]+/)[0]));$('previous').click();await tick();assert.equal($('page-number').value,'1');
$('fullscreen').click();await tick();assert.ok(window.document.body.classList.contains('reading-mode'));assert.equal($('exit-fullscreen').hidden,false);assert.match(window.getComputedStyle($('stage')).backgroundColor,/#000|rgb\(0, 0, 0\)/);assert.equal(window.getComputedStyle($('page-tools')).visibility,'hidden');$('exit-fullscreen').click();await tick();assert.ok(!window.document.body.classList.contains('reading-mode'));
assert.equal($('fullscreen').parentElement.id,'pdf-sheet');$('canvas').dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true}));await tick();assert.ok(window.document.body.classList.contains('reading-mode'));$('canvas').dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true}));await tick();assert.ok(!window.document.body.classList.contains('reading-mode'));
const swipe=(x,y,endX,endY)=>{const start=new window.Event('touchstart',{bubbles:true});Object.defineProperty(start,'touches',{value:[{clientX:x,clientY:y}]});$('canvas').dispatchEvent(start);const end=new window.Event('touchend',{bubbles:true,cancelable:true});Object.defineProperty(end,'touches',{value:[]});Object.defineProperty(end,'changedTouches',{value:[{clientX:endX,clientY:endY}]});$('canvas').dispatchEvent(end);};swipe(180,100,50,100);await tick();assert.equal($('page-number').value,'2');swipe(50,100,180,100);await tick();assert.equal($('page-number').value,'1');swipe(100,180,100,50);await tick();assert.equal($('page-number').value,'1');swipe(100,50,100,180);await tick();assert.equal($('page-number').value,'1');
$('next').click();await tick();assert.equal($('page-number').value,'2');$('next').click();await tick();$('stage').scrollTop=123;swipe(180,100,50,100);await tick();assert.equal($('page-number').value,'3');assert.equal($('stage').scrollTop,123);$('previous').click();await tick();$('larger').click();await tick();assert.ok(renders.includes(2));swipe(180,100,50,100);await tick();assert.equal($('page-number').value,'2');$('file').value='latestPdfFile123';$('file').dispatchEvent(new window.Event('change'));await tick();assert.ok(calls.some(c=>c.fileId==='latestPdfFile123'));assert.equal($('star').disabled,false);$('star').click();await tick();assert.equal(selected,'latestPdfFile123');assert.equal($('star').disabled,true);assert.ok($('file').selectedOptions[0].textContent.startsWith('★'));
$('read-direction').click();await tick();assert.equal($('continuous').hidden,false);assert.equal($('canvas').hidden,true);assert.equal($('continuous').querySelectorAll('.pdf-page').length,3);const slots=[...$('continuous').children];slots.forEach((slot,index)=>Object.defineProperty(slot,'offsetTop',{configurable:true,value:index*parseFloat(slot.style.height)}));Object.defineProperty($('stage'),'clientHeight',{configurable:true,value:600});$('stage').scrollTop=parseFloat(slots[0].style.height)+100;$('stage').dispatchEvent(new window.Event('scroll'));await new Promise(r=>setTimeout(r,50));await tick();assert.equal($('page-number').value,'2');const continuousCanvas=slots[1].querySelector('canvas');continuousCanvas.dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true}));await tick();assert.ok(window.document.body.classList.contains('reading-mode'));$('continuous').querySelector('canvas').dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true}));await tick();assert.ok(!window.document.body.classList.contains('reading-mode'));$('read-direction').click();await tick();assert.equal($('continuous').hidden,true);assert.equal($('canvas').hidden,false);
// Mobile touch double-taps must toggle once even if the browser also sends dblclick.
const tap=(target,x=100,y=100)=>{const start=new window.Event('touchstart',{bubbles:true});Object.defineProperty(start,'touches',{value:[{clientX:x,clientY:y}]});target.dispatchEvent(start);const end=new window.Event('touchend',{bubbles:true,cancelable:true});Object.defineProperty(end,'touches',{value:[]});Object.defineProperty(end,'changedTouches',{value:[{clientX:x+3,clientY:y+2}]});target.dispatchEvent(end);return end;};
assert.match(window.document.querySelector('meta[name="viewport"]').content,/viewport-fit=cover/);
$('fullscreen').click();await tick();assert.ok(window.document.documentElement.classList.contains('reading-mode'));assert.equal(window.document.querySelector('meta[name="theme-color"]').content,'#000000');assert.match(window.getComputedStyle(window.document.documentElement).backgroundColor,/#000|rgb\(0, 0, 0\)/);
tap($('canvas'));assert.equal(tap($('canvas'),108,105).defaultPrevented,true);await tick();assert.ok(!window.document.body.classList.contains('reading-mode'));$('canvas').dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true}));await tick();assert.ok(!window.document.body.classList.contains('reading-mode'),'synthetic dblclick must not re-enter fullscreen');assert.equal(window.document.querySelector('meta[name="theme-color"]').content,'#f3ecdf');assert.ok(!window.document.documentElement.classList.contains('reading-mode'));
tap($('canvas'));tap($('canvas'));await tick();assert.ok(window.document.body.classList.contains('reading-mode'));tap($('stage'));tap($('stage'));await tick();assert.ok(!window.document.body.classList.contains('reading-mode'),'black margins also support exit');
$('read-direction').click();await tick();$('fullscreen').click();await tick();tap($('continuous').querySelector('canvas'));tap($('continuous').querySelector('canvas'));await tick();assert.ok(!window.document.body.classList.contains('reading-mode'),'continuous reading supports mobile double-tap exit');$('read-direction').click();await tick();
$('download').click();await tick();assert.equal(calls.filter(c=>c.path==='/read.pdf').length,1);assert.ok(calls.filter(c=>c.path.endsWith('url')).length>=3);
const desktop=new Window({url:'https://hub.test/pdf.html?folderId=scoreFolder123',settings:{disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:true,suppressInsecureJavaScriptEnvironmentWarning:true}});
try{desktop.happyDOM.setWindowSize({width:1280,height:900});desktop.document.write(fs.readFileSync('public/pdf.html','utf8').replace(/<script[\s\S]*?<\/script>/g,''));desktop.HTMLCanvasElement.prototype.getContext=()=>({drawImage(){}});desktop.pdfTestLib=window.pdfTestLib;desktop.fetch=window.fetch;desktop.eval(fs.readFileSync('public/pdf-viewer.mjs','utf8').replace("await import('/pdfjs.mjs')",'window.pdfTestLib'));await tick();const d=id=>desktop.document.getElementById(id);assert.equal(d('zoom').textContent,'200%');assert.equal(parseFloat(d('canvas').style.width),1200);d('read-direction').click();await tick();assert.equal(d('zoom').textContent,'200%');d('read-direction').click();await tick();d('fit').click();await tick();assert.equal(parseFloat(d('canvas').style.width),1280);d('fullscreen').click();await tick();assert.equal(desktop.getComputedStyle(desktop.document.body).position,'fixed');assert.equal(desktop.getComputedStyle(d('stage')).paddingTop,'0px');d('exit-fullscreen').click();await tick();assert.notEqual(desktop.getComputedStyle(desktop.document.body).position,'fixed');}finally{desktop.happyDOM.abort();desktop.close();}
console.log('PASS: Hub viewer renders selected PDF without automatic download, paginates/zooms, supports black fullscreen/double-click toggling and continuous vertical pages, switches files, saves default stars, and downloads only on click.');
}finally{window.happyDOM.abort();window.close();}
