import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {createDatabase} from '../vercel/database.js';
import {createVoting} from '../vercel/voting.js';
import {createInvitations} from '../vercel/invitations.js';
import {createPlans} from '../vercel/plans.js';
import {createRecordings} from '../vercel/recordings.js';
import worker from '../dist/vercel-worker.mjs';
const postgres=new PGlite();
await postgres.exec(fs.readFileSync('vercel/schema.sql','utf8'));
const query=async(sql,args=[])=>{const r=await postgres.query(sql,args);return {rows:r.rows,rowCount:r.affectedRows??r.rows.length};};
const pool={query,connect:async()=>({query,release(){}})};
const files=new Map();
const storage={async get(key){const v=files.get(key);return v?{async arrayBuffer(){return v.buffer.slice(v.byteOffset,v.byteOffset+v.byteLength)},async text(){return v.toString()},async json(){return JSON.parse(v.toString())}}:null},async put(key,value){files.set(key,Buffer.from(typeof value==='string'?value:await new Response(value).arrayBuffer()))},async delete(key){files.delete(key)}};
const env={DB:createDatabase(pool),FILES:storage,ADMIN_PASSWORD:'test-admin-password',PUBLIC_ORIGIN:'https://hub.test',INVITE_REQUIRED:true,invitations:createInvitations(pool),voting:createVoting(pool)};
env.plans=createPlans(pool);
env.recordings=createRecordings(pool,{...storage,audioUploadUrl:async key=>'https://storage.test/upload/'+key,audioInfo:async key=>({size:files.get(key)?.length||0,contentType:'audio/webm'}),audioPlaybackUrl:async key=>'https://storage.test/play/'+key});
const mf={dispatchFetch:(url,options)=>worker.fetch(new Request(url,options),env),getR2Bucket:async()=>storage,dispose:async()=>postgres.close()};
try {
 const cookies={};
 async function api(path, who='',body=undefined,status=200){
  if(path==='/api/register'&&status===201&&!body.invitationCode)body={...body,invitationCode:(await api('/api/admin/invitations','admin',{},201)).code};
  const headers={};if(who&&cookies[who])headers.Cookie=cookies[who];if(body!==undefined)headers['Content-Type']='application/json';
  const res=await mf.dispatchFetch('https://hub.test'+path,{method:body!==undefined?'POST':'GET',headers,body:body!==undefined?JSON.stringify(body):undefined});
  const raw=await res.text();assert.equal(res.status,status,`${path}: ${raw}`);const set=res.headers.get('set-cookie');if(set&&who)cookies[who]=set.split(';')[0];return raw?JSON.parse(raw):null;
 }
 const home=await mf.dispatchFetch('https://hub.test/');assert.equal(home.status,200);assert.match(await home.text(),/solo|阿卡贝拉/i);
 await api('/api/state','',undefined,401);
 const admin=await api('/api/login','admin',{name:'admin',password:'test-admin-password'});assert.equal(admin.user.isAdmin,true);
 const md=await api('/api/register','md',{name:'Jingwen',password:'abc12345'},201);
 const member=await api('/api/register','member',{name:'Singer',password:'abc12345'},201);
 await api('/api/register','duplicate',{name:'Jingwen',password:'abc12345'},409);
 await api('/api/login','bad',{name:'Jingwen',password:'wrong'},401);
 await api(`/api/admin/users/${md.user.id}`,'admin',{musicDirector:true,arranger:true});
 // Single-part profiles and narrowly scoped Admin/MD delegation.
 let voices=await api(`/api/members/${member.user.id}/voice-parts`,'member',{voiceParts:['alto','alto']});
 assert.deepEqual(voices.profile.voiceParts,['alto']);
 await api(`/api/members/${md.user.id}/voice-parts`,'member',{voiceParts:['bass']},403);
 await api(`/api/members/${member.user.id}/voice-parts`,'md',{voiceParts:['tenor']});
 await api(`/api/members/${member.user.id}/voice-parts`,'member',{voiceParts:['unknown']},400);
 await api(`/api/admin/users/${member.user.id}`,'admin',{president:true});
 await api(`/api/members/${md.user.id}/voice-parts`,'member',{voiceParts:['soprano','alto']},403);
 voices=await api(`/api/members/${md.user.id}/voice-parts`,'admin',{voiceParts:['soprano']});
 assert.deepEqual(voices.members.find(p=>p.id===md.user.id).voiceParts,['soprano']);
 await api(`/api/admin/users/${member.user.id}`,'admin',{president:false});
 await api(`/api/members/${md.user.id}/voice-parts`,'member',{voiceParts:['bass']},403);
 await api('/api/profile','member',{fullName:'Singer',voiceParts:['baritone']});
 assert.deepEqual((await api('/api/state','member')).profile.voiceParts,['baritone']);
 await api('/api/profile','member',{voiceParts:['alto','tenor']},400);
 console.log('PASS: single-part profiles, canonical values, duplicate removal, invalid-part rejection, and Admin/MD-only editing of other members.');
 // Profile opt-in moves members to Crew / Media without granting board roles.
 await api('/api/profile','member',{fullName:'Singer',voiceParts:['alto'],crewMedia:true});
 let crewProfile=(await api('/api/state','member')).profile;assert.equal(crewProfile.isCrew,true);assert.equal(crewProfile.isMedia,false);
 await api('/api/profile','member',{fullName:'Singer',voiceParts:['alto']});assert.equal((await api('/api/state','member')).profile.isCrew,true);
 await api('/api/profile','member',{fullName:'Singer',voiceParts:['alto'],crewMedia:false});assert.equal((await api('/api/state','member')).profile.isCrew,false);
 await api('/api/profile','member',{fullName:'Singer',crewMedia:'yes'},400);
 await api(`/api/members/${member.user.id}/voice-parts`,'md',{voiceParts:['alto'],crewMedia:true});assert.equal((await api('/api/state','member')).profile.isCrew,true);
 await api(`/api/members/${member.user.id}/voice-parts`,'member',{voiceParts:['alto'],crewMedia:false});
 console.log('PASS: self-service Crew / Media opt-in, opt-out, preserved omitted status, delegated editing, and no Media Chair role grant.');
 // Song Plan term history, own signup, delegated lineups, locks, archives and retained snapshots.
 await api('/api/plan','',undefined,401);
 let plan=await api('/api/plan','member');assert.equal(plan.term.label,'2026 Fall');const planTerm=plan.term.id;
 await api('/api/plan/term','member',{label:'2027 Spring'},403);
 await api(`/api/plan/add/${planTerm}`,'member',{title:'Song'},403);
 await api(`/api/plan/add/${planTerm}`,'md',{title:'Jiangnan',folderUrl:'https://example.com/folder'},400);
 plan=await api(`/api/plan/add/${planTerm}`,'md',{title:'Jiangnan',folderUrl:'https://drive.google.com/drive/folders/scoreFolder'});const planSong=plan.songs[0].id;
 assert.equal(plan.songs[0].folderUrl,'https://drive.google.com/drive/folders/scoreFolder');
 await api(`/api/plan/save/${planTerm}`,'member',{changes:[]},403);
 await api(`/api/plan/save/${planTerm}`,'md',{changes:[{action:'entry',id:planSong,body:{memberId:member.user.id,part:'solo'}},{action:'entry',id:planSong,body:{memberId:member.user.id,part:'invalid'}}]},400);
 assert.equal((await api('/api/plan?termId='+planTerm,'md')).songs[0].entries.length,0);
 plan=await api(`/api/plan/save/${planTerm}`,'md',{changes:[{action:'entry',id:planSong,body:{memberId:member.user.id,part:'solo'}},{action:'entry',id:planSong,body:{memberId:member.user.id,part:'solo',remove:true}}]});assert.equal(plan.songs[0].entries.length,0);

 await api(`/api/plan/lock/${planSong}`,'member',{locked:true},403);
 await api(`/api/plan/lock/${planSong}`,'md',{locked:'yes'},400);
 plan=await api(`/api/plan/lock/${planSong}`,'md',{locked:true});assert.equal(plan.songs[0].locked,true);
 await api(`/api/plan/entry/${planSong}`,'member',{part:'alto'},409);
 plan=await api(`/api/plan/lock/${planSong}`,'md',{locked:false});assert.equal(plan.songs[0].locked,false);
 await api(`/api/plan/entry/${planSong}`,'member',{memberId:md.user.id,part:'tenor'},403);
 plan=await api(`/api/plan/entry/${planSong}`,'member',{part:'alto'});assert.ok(plan.songs[0].entries.some(e=>e.part==='alto'));
 plan=await api(`/api/plan/entry/${planSong}`,'member',{part:'tenor'});assert.equal(plan.songs[0].entries.length,2);assert.deepEqual(plan.songs[0].entries.map(e=>e.part).sort(),['alto','tenor']);
 await api(`/api/plan/entry/${planSong}`,'member',{part:'invalid'},400);
 plan=await api(`/api/plan/edit/${planSong}`,'md',{title:'Jiangnan',folderUrl:'',locked:true});assert.equal(plan.songs[0].locked,true);
 await api(`/api/plan/entry/${planSong}`,'member',{part:null},409);
 plan=await api(`/api/plan/entry/${planSong}`,'md',{memberId:member.user.id,part:'alto'});assert.ok(plan.songs[0].entries.some(e=>e.part==='alto'));
 await api(`/api/plan/archive/${planTerm}`,'member',{archived:true},403);
 plan=await api(`/api/plan/archive/${planTerm}`,'md',{archived:true});assert.equal(plan.term.archived,true);const oldName=plan.members.find(m=>m.id===member.user.id).name;
 await api('/api/profile','member',{fullName:'Changed later',voiceParts:['bass']});
 plan=await api('/api/plan?termId='+planTerm,'member');assert.equal(plan.members.find(m=>m.id===member.user.id).name,oldName);
 await api(`/api/plan/entry/${planSong}`,'md',{memberId:member.user.id,part:'bass'},409);
 await api(`/api/plan/delete/${planSong}`,'md',{},409);
 plan=await api('/api/plan/term','md',{label:'2027 Spring'});assert.equal(plan.term.label,'2027 Spring');assert.equal(plan.songs.length,0);assert.equal(plan.terms.length,2);
 assert.equal((await api('/api/plan','member')).term.label,'2027 Spring');
 await api('/api/plan/term','md',{label:'2027 spring'},409);
 plan=await api(`/api/plan/archive/${planTerm}`,'md',{archived:false});assert.equal(plan.term.archived,false);
 await api(`/api/plan/edit/${planSong}`,'md',{title:'Jiangnan',folderUrl:'',locked:false});
 plan=await api(`/api/plan/entry/${planSong}`,'member',{part:null});assert.equal(plan.songs[0].entries.length,0);
 plan=await api(`/api/plan/delete/${planSong}`,'md',{});assert.equal(plan.songs.length,0);
 // Bulk import is atomic, skips existing folders, and retains durable Google retry jobs.
 await api(`/api/plan/bulk/${planTerm}`,'member',{songs:[{title:'Old A',folderUrl:'https://drive.google.com/drive/folders/oldA'}]},403);
 plan=await api(`/api/plan/bulk/${planTerm}`,'md',{songs:[{title:'Old A',folderUrl:'https://drive.google.com/drive/folders/oldA'},{title:'Old B',folderUrl:'https://drive.google.com/drive/folders/oldB'}]});assert.equal(plan.songs.length,2);assert.ok(plan.sheetPending>=2);assert.ok(plan.sheetPendingSongs.some(song=>song.title==='Old A'));assert.deepEqual((await env.plans.list({id:member.user.id},planTerm)).sheetPendingSongs,[]);
 plan=await api(`/api/plan/bulk/${planTerm}`,'md',{songs:[{title:'Old A',folderUrl:'https://drive.google.com/drive/folders/oldA'}]});assert.equal(plan.songs.length,2);
 await api(`/api/plan/bulk/${planTerm}`,'md',{songs:[{title:'Rollback song',folderUrl:'https://drive.google.com/drive/folders/rollback'},{title:'Invalid',folderUrl:'https://bad.example'}]},400);
 assert.equal((await env.plans.list({isMd:true},planTerm)).songs.length,2);
 await env.plans.sync(async()=>{throw Error('temporary_google_failure');});assert.ok((await env.plans.list({isMd:true},planTerm)).sheetPending>0);
 await env.plans.sync(async jobs=>jobs.map(j=>j.id));assert.equal((await env.plans.list({isMd:true},planTerm)).sheetPending,0);
 // Drive semesters seed the same plan; exclusions survive rescan and re-add preserves signup.
 const president=await api('/api/register','president',{name:'PresidentTest',password:'abc12345'},201);
 await api(`/api/admin/users/${president.user.id}`,'admin',{president:true});
 let auto=await env.plans.fromSemester({id:member.user.id},'2028 Fall',[{name:'From Drive',url:'https://drive.google.com/drive/folders/newFolder'}]);
 const autoTerm=auto.term.id,autoSong=auto.songs[0].id;assert.equal(auto.canChoose,false);
 auto=await env.plans.fromSemester({id:member.user.id},'2028fall',[{name:'From Drive',url:'https://drive.google.com/drive/folders/newFolder'}]);assert.equal(auto.term.id,autoTerm);assert.equal(auto.songs.length,1);
 await api(`/api/plan/entry/${autoSong}`,'member',{part:'alto'});
 auto=await api(`/api/plan?termId=${autoTerm}`,'president');assert.equal(auto.canChoose,true);assert.equal(auto.canManage,false);
 await api(`/api/plan/entry/${autoSong}`,'president',{memberId:member.user.id,part:'bass'},403);
 await api(`/api/plan/edit/${autoSong}`,'president',{title:'From Drive',folderUrl:'',locked:true},403);
 await api(`/api/plan/delete/${autoSong}`,'member',{},403);
 auto=await api(`/api/plan/delete/${autoSong}`,'president',{});assert.equal(auto.songs.length,0);
 await api(`/api/plan/entry/${autoSong}`,'member',{part:'bass'},404);
 auto=await env.plans.fromSemester({id:member.user.id},'2028 Fall',[{name:'From Drive',url:'https://drive.google.com/drive/folders/newFolder'}]);assert.equal(auto.songs.length,0);
 auto=await api(`/api/plan/bulk/${autoTerm}`,'president',{songs:[{title:'From Drive',folderUrl:'https://drive.google.com/drive/folders/newFolder'}]});assert.equal(auto.songs[0].id,autoSong);assert.equal(auto.songs[0].entries[0].part,'alto');
 await api(`/api/plan/archive/${autoTerm}`,'md',{archived:true});
 auto=await env.plans.fromSemester({id:member.user.id},'2028 Fall',[{name:'Later folder',url:'https://drive.google.com/drive/folders/laterFolder'}]);assert.equal(auto.songs.length,1);
 await api(`/api/plan/bulk/${autoTerm}`,'president',{songs:[{title:'Cannot change archive'}]},409);
 console.log('PASS: Drive semester auto-population, normalized semester identity, President repertoire-only permissions, persistent exclusions, re-added signups, and immutable archived songs.');
 // Solo delegation, multiple singers/parts, per-part withdrawal, and current-semester archival.
 await api(`/api/plan/entry/${autoSong}`,'member',{part:'solo'},409); // Archived remains read only.
 auto=await api(`/api/plan/current/${autoTerm}`,'md',{});assert.equal(auto.term.isCurrent,true);assert.equal(auto.term.archived,false);assert.ok(auto.terms.filter(t=>t.id!==autoTerm).every(t=>t.archived));
 await api(`/api/plan/current/${planTerm}`,'member',{},403);
 await api(`/api/plan/current/${planTerm}`,'president',{},403);
 await api(`/api/plan/entry/${autoSong}`,'member',{part:'solo'},403);
 auto=await api(`/api/plan/entry/${autoSong}`,'md',{memberId:member.user.id,part:'solo'});assert.ok(auto.songs[0].entries.some(e=>e.part==='solo'));
 await api(`/api/plan/entry/${autoSong}`,'member',{part:'solo',remove:true},403);
 auto=await api(`/api/plan/entry/${autoSong}`,'member',{part:'bass'});assert.ok(auto.songs[0].entries.some(e=>e.part==='alto'));assert.ok(auto.songs[0].entries.some(e=>e.part==='bass'));
 auto=await api(`/api/plan/entry/${autoSong}`,'md',{memberId:md.user.id,part:'bass'});assert.equal(auto.songs[0].entries.filter(e=>e.part==='bass').length,2);
 auto=await api(`/api/plan/entry/${autoSong}`,'member',{part:'bass',remove:true});assert.ok(auto.songs[0].entries.some(e=>e.memberId===member.user.id&&e.part==='alto'));assert.ok(auto.songs[0].entries.some(e=>e.memberId===md.user.id&&e.part==='bass'));
 auto=await api(`/api/plan/entry/${autoSong}`,'member',{part:null});assert.deepEqual(auto.songs[0].entries.filter(e=>e.memberId===member.user.id).map(e=>e.part),['solo']);
 await api(`/api/plan/entry/${autoSong}`,'member',{part:'rap'},400);
 auto=await api(`/api/plan/entry/${autoSong}`,'md',{memberId:member.user.id,part:'solo',remove:true});assert.ok(!auto.songs[0].entries.some(e=>e.part==='solo'));
 auto=await api(`/api/plan/add/${autoTerm}`,'md',{title:'Scores not ready'});const pendingSong=auto.songs.find(s=>s.title==='Scores not ready');assert.equal(pendingSong.folderUrl,'');
 auto=await api(`/api/plan/bulk/${autoTerm}`,'md',{songs:[{title:'Scores not ready',folderUrl:'https://drive.google.com/drive/folders/nowReady'}]});assert.equal(auto.songs.find(s=>s.title==='Scores not ready').id,pendingSong.id);
 // New active singers get a default; existing delegated arrangements stay untouched.
 await api('/api/profile','member',{voiceParts:['alto']});
 await api('/api/profile','md',{voiceParts:['tenor']});
 await api(`/api/plan/entry/${autoSong}`,'md',{memberId:member.user.id,part:'solo'});
 auto=await api(`/api/plan/big/${autoSong}`,'md',{bigSong:true});assert.deepEqual(auto.songs.find(s=>s.id===autoSong).entries.filter(e=>e.memberId===member.user.id).map(e=>e.part).sort(),['alto','solo']);
 await api(`/api/plan/entry/${autoSong}`,'member',{part:'tenor'},409);
 await api(`/api/plan/entry/${autoSong}`,'md',{memberId:member.user.id,part:'alto',remove:true});
 await api(`/api/plan/entry/${autoSong}`,'md',{memberId:member.user.id,part:'bass'});
 await api('/api/profile','member',{voiceParts:['soprano']});
 auto=await api('/api/plan?termId='+autoTerm,'member');assert.deepEqual(auto.songs.find(s=>s.id===autoSong).entries.filter(e=>e.memberId===member.user.id).map(e=>e.part).sort(),['bass','solo']);
 await api(`/api/plan/entry/${autoSong}`,'md',{memberId:member.user.id,part:'tenor'});
 auto=await api('/api/plan?termId='+autoTerm,'member');assert.deepEqual(auto.songs.find(s=>s.id===autoSong).entries.filter(e=>e.memberId===member.user.id).map(e=>e.part).sort(),['bass','solo','tenor']);
 await api('/api/profile','president',{voiceParts:[],crewMedia:true});
 await api(`/api/plan/entry/${autoSong}`,'md',{memberId:president.user.id,part:'alto',remove:true});
 await api('/api/profile','president',{voiceParts:['alto'],crewMedia:false});
 auto=await api('/api/plan?termId='+autoTerm,'member');assert.deepEqual(auto.songs.find(s=>s.id===autoSong).entries.filter(e=>e.memberId===president.user.id).map(e=>e.part),['alto']);
 auto=await api('/api/plan?termId='+autoTerm,'member');assert.equal(auto.songs.find(s=>s.id===autoSong).entries.filter(e=>e.memberId===president.user.id&&e.part==='alto').length,1);
 console.log('PASS: default fill for newly active voiced members, idempotent refresh, unrestricted delegated parts and preserved MD arrangements after profile changes.');
 auto=await api('/api/plan/term','md',{label:'2029 Spring'});assert.equal(auto.term.isCurrent,true);assert.ok(auto.terms.filter(t=>t.id!==auto.term.id).every(t=>t.archived));
 await api(`/api/plan/big/${autoSong}`,'md',{bigSong:false},409);
 const archive=await api('/api/plan?termId='+autoTerm,'member');assert.equal(archive.term.archived,true);assert.ok(archive.songs.find(s=>s.id===autoSong).entries.some(e=>e.part==='bass'));
 console.log('PASS: Solo-only delegated signup, multi-part/multi-singer cells, cross-profile signup, isolated removal, manual titles linked to later scores, single current semester and archived history.');
 console.log('PASS: atomic bulk imports, duplicate folder prevention, preserved plans on Google failure, and durable sync retry completion.');
 console.log('PASS: Song Plan authentication, term selection/history, score-folder validation, own-only registration, signup parts, confirmation locks, delegated edits, archived snapshots and read-only history.');
 // Crew is admin-managed, exclusive with Alumni, and visible in member profiles.
 await api(`/api/admin/users/${member.user.id}`,'member',{crew:true},403);
 await api(`/api/admin/users/${member.user.id}`,'md',{crew:true},403);
 let crewState=await api(`/api/admin/users/${member.user.id}`,'admin',{crew:true});
 assert.equal(crewState.members.find(p=>p.id===member.user.id).isCrew,true);
 await api(`/api/admin/users/${member.user.id}`,'admin',{crew:true,alumni:true},400);
 crewState=await api(`/api/admin/users/${member.user.id}`,'admin',{alumni:true});
 assert.equal(crewState.members.find(p=>p.id===member.user.id).isCrew,false);
 assert.equal(crewState.members.find(p=>p.id===member.user.id).isAlumni,true);
 crewState=await api(`/api/admin/users/${member.user.id}`,'admin',{crew:true});
 assert.equal(crewState.members.find(p=>p.id===member.user.id).isAlumni,false);
 await api(`/api/admin/users/${member.user.id}`,'admin',{crew:false});
 await api('/api/phases','member',{title:'Love Yourself',arrangerId:md.user.id},403);
 await api('/api/phases','md',{title:'Invalid song',arrangerId:md.user.id,planSongId:999999},404);
 const currentPlan=await api('/api/plan','md');const linkedPlan=await api(`/api/plan/add/${currentPlan.term.id}`,'md',{title:'Love Yourself'});const linkedSongId=linkedPlan.songs.find(s=>s.title==='Love Yourself').id;
 const round=await api('/api/phases','md',{planSongId:linkedSongId,title:'Round 1',arrangerId:md.user.id,votingMode:'feedback'},201);assert.equal(round.phase.title,'Love Yourself-Round 1');
 const phaseId=round.phase.id;assert.equal((await api('/api/plan/results?songId='+linkedSongId,'member')).history.length,0);
 await api(`/api/phases/${phaseId}/candidacy`,'member',{join:true});
 await api(`/api/phases/${phaseId}/candidacy`,'md',{join:true});
 await api(`/api/phases/${phaseId}/start`,'md',{});
 await api(`/api/phases/${phaseId}/vote`,'md',{candidateId:member.user.id,reaction:'like'});
 let state=await api('/api/state','md');assert.equal(state.phase.candidates[0].likes,undefined);
 state=await api('/api/state','member');assert.equal(state.phase.candidates[0].likes,undefined);
 await api(`/api/phases/${phaseId}/vote`,'md',{candidateId:member.user.id,reaction:'again'});
 state=await api('/api/state','md');assert.equal(state.phase.candidates.find(c=>c.id===member.user.id).mine,'again');
 await api(`/api/phases/${phaseId}/close`,'member',{},403);

 await api('/api/profile','member',{fullName:'Singer Zhang',voicePart:'Alto',school:'Columbia',gradYear:'2027',funFact:'Loves music'});
 const form=new FormData();form.set('avatar',new Blob([fs.readFileSync('public/icon-192.png')],{type:'image/png'}),'avatar.png');
 const uploadRequest=new Request('https://hub.test/api/profile/avatar',{method:'POST',body:form});
 let r=await mf.dispatchFetch(uploadRequest.url,{method:'POST',headers:{Cookie:cookies.member,'Content-Type':uploadRequest.headers.get('content-type')},body:await uploadRequest.arrayBuffer()});assert.equal(r.status,200,await r.text());
 r=await mf.dispatchFetch(`https://hub.test/api/avatars/${member.user.id}`,{headers:{Cookie:cookies.md}});assert.equal(r.status,200);assert.equal((await r.arrayBuffer()).byteLength,fs.statSync('public/icon-192.png').size);

 // Photo gallery: legacy preservation, cross-member upload, ownership checks, selection and deletion.
 const outsider=await api('/api/register','outsider',{name:'Other singer',password:'abc12345'},201);
 const albumPath='/api/profiles/'+member.user.id+'/photos';
 await api(albumPath,'',undefined,401);
 let album=await api(albumPath,'md');assert.equal(album.photos.length,1);const legacy=album.photos[0];assert.equal(legacy.isAvatar,true);
 async function uploadPhoto(who,bytes=fs.readFileSync('public/icon-192.png'),type='image/png',filename='photo.png',status=201){
  const form=new FormData();form.set('photo',new Blob([bytes],{type}),filename);
  const req=new Request('https://hub.test'+albumPath,{method:'POST',body:form});
  const r=await mf.dispatchFetch(req.url,{method:'POST',headers:{Cookie:cookies[who],'Content-Type':req.headers.get('content-type')},body:await req.arrayBuffer()});
  const body=await r.json();assert.equal(r.status,status,JSON.stringify(body));return body;
 }
 album=await uploadPhoto('md');const added=album.photos.find(p=>p.id!==legacy.id);assert.equal(added.name,'Jingwen');assert.equal(added.canDelete,true);assert.equal(added.canSetAvatar,false);
 await uploadPhoto('md',Buffer.from('not an image'),'image/png','photo.png',400);
 await api('/api/photos/'+added.id+'/avatar','md',{},403);
 await api('/api/photos/'+added.id+'/delete','outsider',{},403);
 await api('/api/photos/'+legacy.id+'/delete','md',{},403);
 await api('/api/photos/'+added.id+'/avatar','member',{});
 album=await api(albumPath,'member');assert.equal(album.photos.find(p=>p.id===added.id).isAvatar,true);assert.equal(album.photos.every(p=>p.canDelete&&p.canSetAvatar),true);
 r=await mf.dispatchFetch('https://hub.test/api/photos/'+added.id,{headers:{Cookie:cookies.outsider}});assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/png');
 await api('/api/photos/'+added.id+'/delete','md',{});
 state=await api('/api/state','member');assert.equal(state.profile.avatar,'');
 album=await api(albumPath,'member');assert.equal(album.photos.length,1);
 await api('/api/photos/'+legacy.id+'/avatar','member',{});
 await api('/api/photos/'+legacy.id+'/delete','member',{});
 album=await api(albumPath,'member');assert.equal(album.photos.length,0);

 // Likes are unique, reversible and private; manual avatars override automatic winners.
 album=await uploadPhoto('md');const likedA=album.photos[0];album=await uploadPhoto('outsider');const likedB=album.photos.find(p=>p.id!==likedA.id);
 await api('/api/photos/'+likedA.id+'/like','', {liked:true},401);
 await api('/api/photos/'+likedA.id+'/like','md', {liked:'true'},400);
 await api('/api/photos/'+likedA.id+'/like','md', {liked:true});album=await api('/api/photos/'+likedA.id+'/like','md', {liked:true});assert.equal(album.photos.find(p=>p.id===likedA.id).likes,1);
 state=await api('/api/state','member');assert.equal(state.profile.avatar,'/api/photos/'+likedA.id);
 await api('/api/photos/'+likedB.id+'/like','md',{liked:true});state=await api('/api/state','member');assert.equal(state.profile.avatar,'/api/photos/'+likedA.id);
 await api('/api/photos/'+likedB.id+'/avatar','member',{});await api('/api/photos/'+likedA.id+'/like','outsider',{liked:true});state=await api('/api/state','member');assert.ok(state.profile.avatar.startsWith('/api/avatars/'));
 await api('/api/photos/'+likedB.id+'/clear-avatar','md',{},403);await api('/api/photos/'+likedB.id+'/clear-avatar','member',{});state=await api('/api/state','member');assert.equal(state.profile.avatar,'/api/photos/'+likedA.id);
 await api('/api/photos/'+likedB.id+'/like','md',{liked:false});await api('/api/photos/'+likedA.id+'/like','md',{liked:false});await api('/api/photos/'+likedA.id+'/like','outsider',{liked:false});state=await api('/api/state','member');assert.equal(state.profile.avatar,'');
 await api('/api/photos/'+likedB.id+'/like','md',{liked:true});state=await api('/api/state','member');assert.equal(state.profile.avatar,'/api/photos/'+likedB.id);await api('/api/photos/'+likedB.id+'/delete','outsider',{});state=await api('/api/state','member');assert.equal(state.profile.avatar,'');assert.equal((await query('SELECT count(*)::int AS n FROM cucac.photo_likes WHERE photo_id=$1',[likedB.id])).rows[0].n,0);
 await api('/api/photos/'+likedA.id+'/delete','md',{});
 console.log('PASS: unique/idempotent photo likes, unlike, automatic highest-liked avatars, manual override and cancellation, zero-like initials, delegated rejection and cascading deletion.');
 await api(`/api/phases/${phaseId}/close`,'md',{});
 const soloAfterClose=(await api('/api/plan?termId='+currentPlan.term.id,'member')).songs.find(s=>s.id===linkedSongId).entries.filter(e=>e.part==='solo');assert.equal(soloAfterClose.length,0);
 await api(`/api/phases/${phaseId}/edit`,'member',{title:'Changed',planSongId:linkedSongId},403);
 const beforeEditVotes=(await query('SELECT * FROM cucac.votes WHERE phase_id=$1 ORDER BY voter_id,candidate_id',[phaseId])).rows;
 let edited=await api(`/api/phases/${phaseId}/edit`,'md',{title:'Revised round',planSongId:pendingSong.id});assert.equal(edited.history[0].title,'Scores not ready-Revised round');assert.equal((await api('/api/plan/results?songId='+linkedSongId,'member')).history.length,0);assert.equal((await api('/api/plan/results?songId='+pendingSong.id,'member')).history[0].id,phaseId);assert.deepEqual((await query('SELECT * FROM cucac.votes WHERE phase_id=$1 ORDER BY voter_id,candidate_id',[phaseId])).rows,beforeEditVotes);
 edited=await api(`/api/phases/${phaseId}/edit`,'md',{title:'Unlinked',planSongId:null});assert.equal(edited.history[0].title,'Unlinked');
 await api(`/api/phases/${phaseId}/edit`,'md',{title:'',planSongId:linkedSongId},400);
 await api(`/api/phases/${phaseId}/edit`,'md',{title:'Round 1',planSongId:linkedSongId});
 const linkedHistory=await api('/api/plan/results?songId='+linkedSongId,'member');assert.equal(linkedHistory.history[0].id,phaseId);assert.ok(linkedHistory.history[0].candidates.every(c=>c.rank<=linkedHistory.history[0].revealedRanks&&!('likes' in c)));

 state=await api('/api/state','md');assert.equal(state.phase,null);assert.equal(state.history[0].candidates[0].again,undefined);
 await api('/api/google/settings','member',{clientId:'x'},403);
 await api('/api/google/settings','admin',{clientId:'test.apps.googleusercontent.com',clientSecret:'test-secret',spreadsheet:'',parentFolder:''});
 r=await mf.dispatchFetch('https://hub.test/api/google/connect',{headers:{Cookie:cookies.admin},redirect:'manual'});assert.equal(r.status,302);assert.equal(new URL(r.headers.get('location')).searchParams.get('redirect_uri'),'https://hub.test/api/google/callback');
 const preservedResults=(await api('/api/state','admin')).history.find(p=>p.id===phaseId).candidates;
 await query('UPDATE cucac.phases SET solo_results=NULL WHERE id=$1',[phaseId]);await postgres.exec(fs.readFileSync('vercel/solo-results-schema.sql','utf8'));await postgres.exec(fs.readFileSync('vercel/solo-results-schema.sql','utf8'));assert.deepEqual((await api('/api/state','admin')).history.find(p=>p.id===phaseId).candidates,preservedResults);
 album=await uploadPhoto('md');const cleanupPhoto=album.photos[0];
 await api(`/api/admin/users/${member.user.id}/delete`,'admin',{});
 await postgres.exec(fs.readFileSync('vercel/solo-results-schema.sql','utf8'));
 assert.deepEqual((await api('/api/state','admin')).history.find(p=>p.id===phaseId).candidates,preservedResults);
 const retainedPublic=(await api('/api/plan/results?songId='+linkedSongId,'md')).history.find(p=>p.id===phaseId);assert.ok(retainedPublic.candidates.some(c=>c.id===member.user.id));assert.ok(retainedPublic.candidates.every(c=>!('likes' in c)&&!('again' in c)));
 await api(`/api/phases/${phaseId}/delete`,'admin',{});
 console.log('PASS: immutable Solo history survives candidate/voter deletion, migration backfill is idempotent, linked results retain deleted names and private counts remain protected.');
 await api('/api/photos/'+cleanupPhoto.id,'md',undefined,404);
 const photoFiles=await mf.getR2Bucket('FILES');assert.equal(await photoFiles.get('photos/'+cleanupPhoto.id+'.png'),null);
 state=await api('/api/state','md');assert.equal(state.members.some(x=>x.id===member.user.id),false);
 await api('/api/register','blocked',{name:'Uninvited',password:'abc12345'},403);
 await api('/api/admin/invitations','md',{},403);
 const invite=await api('/api/admin/invitations','admin',{},201);
 await api('/api/register','invited',{name:'Invited',password:'abc12345',invitationCode:invite.code},201);
 await api('/api/register','reused',{name:'Reused',password:'abc12345',invitationCode:invite.code},201);
 assert.equal((await query('SELECT use_count FROM cucac.invitations WHERE id=$1',[invite.id])).rows[0].use_count,2);
 const single=await api('/api/admin/invitations','admin',{},201);
 await query('UPDATE cucac.invitations SET is_shared=0 WHERE id=$1',[single.id]);
 await api('/api/register','single',{name:'Single',password:'abc12345',invitationCode:single.code},201);
 await api('/api/register','single2',{name:'Single2',password:'abc12345',invitationCode:single.code},403);
 const revoked=await api('/api/admin/invitations','admin',{},201);
 await api('/api/admin/invitations/'+revoked.id+'/revoke','admin',{});
 await api('/api/register','revoked',{name:'Revoked',password:'abc12345',invitationCode:revoked.code},403);
 const expired=await api('/api/admin/invitations','admin',{},201);
 await query('UPDATE cucac.invitations SET expires_at=$1 WHERE id=$2',['2000-01-01',expired.id]);
 await api('/api/register','expired',{name:'Expired',password:'abc12345',invitationCode:expired.code},403);
 const reusable=await api('/api/admin/invitations','admin',{},201);
 await assert.rejects(env.invitations.register({code:reusable.code,name:'Jingwen',passwordHash:'test',createdAt:new Date().toISOString()}),e=>e.message==='name_taken');
 await api('/api/register','retry',{name:'Retry',password:'abc12345',invitationCode:reusable.code},201);
 await api('/api/login','case',{name:'jINGWEN',password:'abc12345'});
 await assert.rejects(env.DB.batch([env.DB.prepare('INSERT INTO arrangers(name,created_at) VALUES(?,?)').bind('Rollback probe','now'),env.DB.prepare('INSERT INTO arrangers(name,created_at) VALUES(?,?)').bind('Rollback probe','now')]));
 assert.equal((await query("SELECT * FROM cucac.arrangers WHERE name='Rollback probe'")).rows.length,0);
 const privateTables=(await query("SELECT tablename,rowsecurity FROM pg_tables WHERE schemaname='cucac'")).rows;assert.ok(privateTables.every(t=>t.rowsecurity));assert.ok(privateTables.some(t=>t.tablename==='plan_cast'));

 // Default voting: preparation, two-candidate lock, cancellation, and server-side limits.
 let v=await api('/api/phases','md',{title:'Two singers',arrangerId:md.user.id},201);
 let vid=v.phase.id;assert.equal(v.phase.votingMode,'default');assert.equal(v.phase.started,false);
 await api(`/api/phases/${vid}/candidacy`,'md',{join:true});
 await api(`/api/phases/${vid}/candidacy`,'outsider',{join:true});
 await api(`/api/phases/${vid}/vote`,'md',{candidateId:md.user.id,reaction:'like'},403);
 await api(`/api/phases/${vid}/start`,'outsider',{},403);
 v=await api(`/api/phases/${vid}/start`,'md',{});assert.equal(v.phase.registrationLocked,true);
 await api(`/api/phases/${vid}/candidacy`,'retry',{join:true},403);
 await api(`/api/phases/${vid}/vote`,'retry',{candidateId:md.user.id,reaction:'like'});
 await api(`/api/phases/${vid}/vote`,'retry',{candidateId:outsider.user.id,reaction:'like'},400);
 await api(`/api/phases/${vid}/vote`,'retry',{candidateId:md.user.id,reaction:null});
 await api(`/api/phases/${vid}/vote`,'retry',{candidateId:outsider.user.id,reaction:'like'});
 await api(`/api/phases/${vid}/vote`,'retry',{candidateId:md.user.id,reaction:'again'},400);
 await api(`/api/phases/${vid}/close`,'md',{});
 // Five singers: initial random order persists and late registrations append.
 v=await api('/api/phases','md',{title:'Shared ranks',arrangerId:md.user.id},201);vid=v.phase.id;
 for(const who of ['md','outsider','retry'])await api(`/api/phases/${vid}/candidacy`,who,{join:true});
 v=await api(`/api/phases/${vid}/start`,'md',{});const order=v.phase.candidates.map(c=>c.id);
 assert.deepEqual([...order].sort((a,b)=>a-b),[md.user.id,outsider.user.id,(await api('/api/state','retry')).user.id].sort((a,b)=>a-b));
 assert.deepEqual((await api('/api/state','md')).phase.candidates.map(c=>c.id),order);
 v=await api(`/api/phases/${vid}/candidacy`,'invited',{join:true});const fourth=v.user.id;
 assert.deepEqual(v.phase.candidates.slice(0,3).map(c=>c.id),order);assert.equal(v.phase.candidates.at(-1).id,fourth);
 v=await api(`/api/phases/${vid}/candidacy`,'single',{join:true});const fifth=v.user.id;
 const ids=v.phase.candidates.map(c=>c.id);
 await api(`/api/phases/${vid}/vote`,'md',{candidateId:ids[0],reaction:'like'});
 await api(`/api/phases/${vid}/vote`,'md',{candidateId:ids[1],reaction:'like'});
 await api(`/api/phases/${vid}/vote`,'md',{candidateId:ids[2],reaction:'like'},400);
 // Fixture for two ties at each of ranks 1 and 2, plus one lower rank.
 await query('DELETE FROM cucac.votes WHERE phase_id=$1',[vid]);
 const voterIds=(await query('SELECT id FROM cucac.users ORDER BY id')).rows.map(r=>r.id);
 for(let ci=0;ci<5;ci++)for(let j=0;j<[3,3,2,2,1][ci];j++)await query('INSERT INTO cucac.votes(phase_id,voter_id,candidate_id,reaction) VALUES($1,$2,$3,$4)',[vid,voterIds[j],ids[ci],'like']);
 v=await api(`/api/phases/${vid}/close`,'md',{});
 let results=v.history.find(r=>r.id===vid);assert.equal(results.candidates.length,4);assert.deepEqual(results.candidates.map(c=>c.rank),[1,1,2,2]);
 for(const c of results.candidates){assert.equal(c.likes,undefined);assert.equal(c.again,undefined);assert.equal(c.mine,undefined);}
 let adminResults=(await api('/api/state','admin')).history.find(r=>r.id===vid);assert.equal(adminResults.candidates.length,5);assert.deepEqual(adminResults.candidates.map(c=>c.likes),[3,3,2,2,1]);
 assert.equal(adminResults.canSeeResults,true);assert.equal(adminResults.canReveal,false);
 assert.equal(adminResults.candidates.at(-1).rank,3);assert.equal(adminResults.candidates.at(-1).likes,1);
 assert.equal(results.canReveal,true);
 await api(`/api/phases/${vid}/reveal`,'admin',{},403);
 assert.equal((await api('/api/state','admin')).history.find(r=>r.id===vid).revealedRanks,2);
 assert.equal((await api('/api/state','outsider')).history.find(r=>r.id===vid).candidates.length,4);
 await api(`/api/phases/${vid}/reveal`,'outsider',{},403);
 await api(`/api/phases/${vid}/reveal`,'md',{});
 results=(await api('/api/state','outsider')).history.find(r=>r.id===vid);assert.equal(results.candidates.length,5);assert.equal(results.candidates.at(-1).rank,3);assert.equal(results.candidates.at(-1).likes,undefined);
 // Duet pair voting: invitations require the other member's confirmation.
 let duet=await api('/api/phases','md',{title:'Two pairs',arrangerId:md.user.id,pollType:'pair'},201);
 let did=duet.phase.id;
 const users={md:md.user.id,outsider:outsider.user.id,retry:(await api('/api/state','retry')).user.id,invited:(await api('/api/state','invited')).user.id,single:(await api('/api/state','single')).user.id};
 await api(`/api/phases/${did}/pair`,'md',{partnerId:users.md},400);
 await api(`/api/phases/${did}/pair`,'md',{partnerId:users.outsider,auditionUrl:'javascript:alert(1)'},400);
 duet=await api(`/api/phases/${did}/pair`,'md',{partnerId:users.outsider,auditionUrl:'https://drive.google.com/test'});
 assert.equal(duet.phase.candidates.length,0);assert.equal(duet.phase.pendingPairs.length,1);
 assert.equal((await api('/api/state','retry')).phase.pendingPairs.length,0);
 const first=duet.phase.pendingPairs[0].id;
 await api(`/api/phases/${did}/pair`,'outsider',{partnerId:users.md},409);
 await api(`/api/phases/${did}/confirm`,'md',{entryId:first},403);
 await api(`/api/phases/${did}/confirm`,'retry',{entryId:first},403);
 duet=await api(`/api/phases/${did}/confirm`,'outsider',{entryId:first});assert.equal(duet.phase.candidates.length,1);
 await api(`/api/phases/${did}/start`,'md',{},400);
 duet=await api(`/api/phases/${did}/pair`,'retry',{partnerId:users.invited});const second=duet.phase.pendingPairs[0].id;
 await api(`/api/phases/${did}/confirm`,'invited',{entryId:second});
 duet=await api(`/api/phases/${did}/pair`,'single',{partnerId:users.md});const pending=duet.phase.pendingPairs[0].id;
 duet=await api(`/api/phases/${did}/start`,'md',{});assert.equal(duet.phase.registrationLocked,true);
 await api(`/api/phases/${did}/confirm`,'md',{entryId:pending},403);
 await api(`/api/phases/${did}/vote`,'single',{entryId:pending,reaction:'like'},400);
 await api(`/api/phases/${did}/pair`,'single',{partnerId:users.invited},403);
 await api(`/api/phases/${did}/vote`,'md',{entryId:first,reaction:'like'});
 await api(`/api/phases/${did}/vote`,'md',{entryId:second,reaction:'like'},400);
 await api(`/api/phases/${did}/vote`,'md',{entryId:first,reaction:null});
 duet=await api(`/api/phases/${did}/vote`,'md',{entryId:second,reaction:'like'});assert.equal(duet.phase.candidates.find(e=>e.id===second).mine,'like');
 assert.equal(duet.phase.candidates.find(e=>e.id===second).likes,undefined);
 await api(`/api/phases/${did}/cancel`,'md',{entryId:first},403);
 await api(`/api/phases/${did}/audition`,'retry',{entryId:first,auditionUrl:'https://example.org'},403);
 await api(`/api/phases/${did}/close`,'md',{});
 let duoHistory=(await api('/api/state','md')).history.find(h=>h.id===did);assert.equal(duoHistory.pollType,'pair');assert.equal(duoHistory.candidates.every(e=>e.likes===undefined&&e.mine===undefined),true);
 assert.equal((await api('/api/state','admin')).history.find(h=>h.id===did).candidates[0].likes,1);
 await api(`/api/phases/${did}/reveal`,'admin',{},403);
 await api(`/api/phases/${did}/audition`,'md',{entryId:first,auditionUrl:'https://example.org'},400);

 // Three-pair ballots permit two choices and append later confirmed pairs.
 duet=await api('/api/phases','md',{title:'Open pairs',arrangerId:md.user.id,pollType:'pair'},201);did=duet.phase.id;
 const pairs=[];
 for(const partner of ['outsider','retry','invited']){duet=await api(`/api/phases/${did}/pair`,'md',{partnerId:users[partner]});const entry=duet.phase.pendingPairs.find(e=>e.members.some(m=>m.id===users[partner]));pairs.push(entry.id);await api(`/api/phases/${did}/confirm`,partner,{entryId:entry.id});}
 duet=await api(`/api/phases/${did}/start`,'md',{});const pairOrder=duet.phase.candidates.map(e=>e.id);assert.equal(duet.phase.registrationLocked,false);
 await api(`/api/phases/${did}/vote`,'single',{entryId:pairs[0],reaction:'like'});
 await api(`/api/phases/${did}/vote`,'single',{entryId:pairs[1],reaction:'like'});
 await api(`/api/phases/${did}/vote`,'single',{entryId:pairs[2],reaction:'like'},400);
 duet=await api(`/api/phases/${did}/pair`,'single',{partnerId:users.md});const late=duet.phase.pendingPairs[0].id;
 duet=await api(`/api/phases/${did}/confirm`,'md',{entryId:late});assert.deepEqual(duet.phase.candidates.slice(0,3).map(e=>e.id),pairOrder);assert.equal(duet.phase.candidates.at(-1).id,late);
 await api(`/api/phases/${did}/cancel`,'single',{entryId:late});
 await api(`/api/phases/${did}/cancel`,'md',{entryId:pairs[0]},403);
 await api(`/api/phases/${did}/close`,'md',{});

 // Independent part ballots, custom labels, one-part registration and per-part ties.
 const extra=await api('/api/register','sixth',{name:'Duet sixth',password:'abc12345'},201);users.sixth=extra.user.id;
 duet=await api('/api/phases','md',{title:'Part voting',arrangerId:md.user.id,pollType:'parts',partA:'High voice',partB:'Low voice'},201);did=duet.phase.id;
 assert.equal(duet.phase.partA,'High voice');assert.equal(duet.phase.partB,'Low voice');
 await api(`/api/phases/${did}/candidacy`,'md',{join:true,part:'A'});
 await api(`/api/phases/${did}/start`,'md',{},400);
 await api(`/api/phases/${did}/candidacy`,'md',{join:true,part:'B'},409);
 for(const who of ['outsider','retry'])await api(`/api/phases/${did}/candidacy`,who,{join:true,part:'A'});
 for(const who of ['invited','single','sixth'])await api(`/api/phases/${did}/candidacy`,who,{join:true,part:'B'});
 duet=await api(`/api/phases/${did}/start`,'md',{});
 assert.deepEqual(duet.phase.voteLimits,{A:2,B:2});assert.deepEqual(duet.phase.partLocks,{A:false,B:false});
 const aEntries=duet.phase.candidates.filter(e=>e.part==='A'),bEntries=duet.phase.candidates.filter(e=>e.part==='B');
 for(const entry of [...aEntries.slice(0,2),...bEntries.slice(0,2)])await api(`/api/phases/${did}/vote`,'md',{entryId:entry.id,reaction:'like'});
 await api(`/api/phases/${did}/vote`,'md',{entryId:aEntries[2].id,reaction:'like'},400);
 await api(`/api/phases/${did}/vote`,'md',{entryId:bEntries[2].id,reaction:'like'},400);
 await api(`/api/phases/${did}/cancel`,'md',{entryId:aEntries.find(e=>e.isMe).id},403);
 await query('DELETE FROM cucac.duet_votes WHERE phase_id=$1',[did]);
 for(const entries of [aEntries,bEntries])for(let i=0;i<3;i++)for(let j=0;j<(entries===bEntries?[3,2,2]:[3,2,1])[i];j++)await query('INSERT INTO cucac.duet_votes(phase_id,entry_id,voter_id) VALUES($1,$2,$3)',[did,entries[i].id,voterIds[j]]);
 await api(`/api/phases/${did}/close`,'md',{});
 duoHistory=(await api('/api/state','single')).history.find(h=>h.id===did);assert.deepEqual(duoHistory.candidates.map(e=>e.rank),[1,2,1,2,2]);assert.equal(duoHistory.candidates.every(e=>e.likes===undefined&&e.mine===undefined),true);
 assert.equal((await api('/api/state','admin')).history.find(h=>h.id===did).candidates.length,6);
 await api(`/api/phases/${did}/reveal`,'admin',{},403);
 await api(`/api/phases/${did}/reveal`,'md',{});
 assert.deepEqual((await api('/api/state','single')).history.find(h=>h.id===did).candidates.map(e=>e.rank),[1,2,3,1,2,2]);
 await api(`/api/phases/${did}/delete`,'admin',{});
 assert.equal((await query('SELECT count(*)::int AS n FROM cucac.duet_entries WHERE phase_id=$1',[did])).rows[0].n,0);
 assert.equal((await query('SELECT count(*)::int AS n FROM cucac.duet_votes WHERE phase_id=$1',[did])).rows[0].n,0);

 duet=await api('/api/phases','md',{title:'Small parts',arrangerId:md.user.id,pollType:'parts'},201);did=duet.phase.id;
 for(const who of ['md','outsider'])await api(`/api/phases/${did}/candidacy`,who,{join:true,part:'A'});
 await api(`/api/phases/${did}/candidacy`,'single',{join:true,part:'B'});
 duet=await api(`/api/phases/${did}/start`,'md',{});assert.deepEqual(duet.phase.voteLimits,{A:1,B:1});
 await api(`/api/phases/${did}/candidacy`,'sixth',{join:true,part:'A'},403);
 await api(`/api/phases/${did}/candidacy`,'sixth',{join:true,part:'B'},403);
 const smallA=duet.phase.candidates.filter(e=>e.part==='A');
 await api(`/api/phases/${did}/vote`,'sixth',{entryId:smallA[0].id,reaction:'like'});
 await api(`/api/phases/${did}/vote`,'sixth',{entryId:smallA[1].id,reaction:'like'},400);
 await api(`/api/phases/${did}/vote`,'sixth',{entryId:duet.phase.candidates.find(e=>e.part==='B').id,reaction:'like'});
 // Private recording upload authorization, playback and one-week expiration.
 const audioEntry=duet.phase.candidates.find(e=>e.members.some(m=>m.id===users.md));
 await api(`/api/phases/${did}/recordings`,'',{entryId:audioEntry.id,mime:'audio/webm',size:10},401);
 await api(`/api/phases/${did}/recordings`,'sixth',{entryId:audioEntry.id,mime:'audio/webm',size:10},403);
 await api(`/api/phases/${did}/recordings`,'md',{entryId:audioEntry.id,mime:'text/html',size:10},400);
 await api(`/api/phases/${did}/recordings`,'md',{entryId:audioEntry.id,mime:'audio/webm',size:51*1024*1024},413);
 async function putAudio(who,phaseId,target){const upload=await api(`/api/phases/${phaseId}/recordings`,who,{...target,mime:'audio/webm',size:10},201);const key=(await query('SELECT object_key FROM cucac.recordings WHERE id=$1',[upload.id])).rows[0].object_key;files.set(key,Buffer.from('audio data'));await api(`/api/recordings/${upload.id}/complete`,who,{});return {...upload,key};}
 const clip=await putAudio('md',did,{entryId:audioEntry.id});
 let audioState=await api('/api/state','sixth');assert.equal(audioState.phase.recordings.length,1);assert.equal(audioState.phase.recordings[0].canDelete,false);
 await api(`/api/recordings/${clip.id}/delete`,'sixth',{},403);
 r=await mf.dispatchFetch(`https://hub.test/api/recordings/${clip.id}`);assert.equal(r.status,401);
 r=await mf.dispatchFetch(`https://hub.test/api/recordings/${clip.id}`,{headers:{Cookie:cookies.sixth}});assert.equal(r.status,302);assert.match(r.headers.get('location'),/^https:\/\/storage.test\/play\//);
 await query("UPDATE cucac.recordings SET created_at=now()-interval '30 days' WHERE id=$1",[clip.id]);
 await env.recordings.cleanup();assert.equal(files.has(clip.key),true); // Open voting retains recordings regardless of creation age.
 await api(`/api/phases/${did}/close`,'md',{});
 audioState=await api('/api/state','sixth');assert.equal(audioState.history.find(h=>h.id===did).recordings.length,1);
 await query("UPDATE cucac.phases SET closed_at=(now()-interval '8 days')::text WHERE id=$1",[did]);
 r=await mf.dispatchFetch(`https://hub.test/api/recordings/${clip.id}`,{headers:{Cookie:cookies.sixth}});assert.equal(r.status,410);
 assert.equal((await api('/api/state','sixth')).history.find(h=>h.id===did).recordings.length,0);
 await env.recordings.cleanup();assert.equal(files.has(clip.key),false);assert.equal((await query('SELECT 1 FROM cucac.recordings WHERE id=$1',[clip.id])).rows.length,0);
 // Either confirmed partner can delete a pair's recording, but only the uploader can finalize an upload.
 duet=await api('/api/phases','md',{title:'Pair recording',arrangerId:md.user.id,pollType:'pair'},201);did=duet.phase.id;
 duet=await api(`/api/phases/${did}/pair`,'md',{partnerId:users.outsider});const audioPair=duet.phase.pendingPairs[0].id;
 await api(`/api/phases/${did}/recordings`,'md',{entryId:audioPair,mime:'audio/webm',size:10},403);
 await api(`/api/phases/${did}/confirm`,'outsider',{entryId:audioPair});
 const pairedClip=await putAudio('outsider',did,{entryId:audioPair});
 await api(`/api/recordings/${pairedClip.id}/complete`,'md',{},403);
 await api(`/api/recordings/${pairedClip.id}/delete`,'md',{});assert.equal(files.has(pairedClip.key),false);
 await api(`/api/phases/${did}/close`,'md',{});
 duet=await api('/api/phases','md',{title:'Solo recording',arrangerId:md.user.id},201);did=duet.phase.id;
 await api(`/api/phases/${did}/recordings`,'md',{candidateId:users.md,mime:'audio/webm',size:10},400);
 await api(`/api/phases/${did}/candidacy`,'md',{join:true});
 const soloClip=await putAudio('md',did,{candidateId:users.md});
 await api(`/api/phases/${did}/recordings`,'single',{candidateId:users.md,mime:'audio/webm',size:10},403);
 await api(`/api/phases/${did}/candidacy`,'md',{join:false});assert.equal((await api('/api/state','md')).phase.recordings.length,0);
 await query("UPDATE cucac.recordings SET created_at=now()-interval '2 days' WHERE id=$1",[soloClip.id]);await env.recordings.cleanup();assert.equal(files.has(soloClip.key),false);
 if(process.env.PLAN_UI_FIXTURE)fs.writeFileSync(process.env.PLAN_UI_FIXTURE,JSON.stringify(await api('/api/state','md')));
 console.log('PASS: recording ownership, signed upload flow, confirmed-pair sharing, authenticated playback, no creation-age limit in open rounds, exact post-close expiry, private history recordings, and storage cleanup.');

 console.log('PASS: pair confirmation, invitation ownership, shared singers, locked two-pair ballot, two-choice pair ballot, late confirmation order, per-part limits/ranks/privacy, MD reveal, audition URL validation and cascade cleanup.');

 console.log('PASS: default voting limits, start permissions, locked two-singer registration, persistent shuffled order, late appends, dense ties, admin-only counts, MD reveal, and private result API.');
 console.log('PASS: PostgreSQL adapter, invite-required registration, single-use/expiry/revocation/rollback, case-insensitive login, private schema; Worker runtime, registration/login, roles, shared votes, result visibility, profile/avatar, gallery permissions and cleanup, history, deletion, Google redirect/config.');
} finally {await mf.dispose();}
