import fs from 'node:fs';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
const window=new Window({url:'https://hub.test/pdf.html?folderId=scoreFolder123',settings:{disableJavaScriptFileLoading:true,disableCSSFileLoading:true,enableJavaScriptEvaluation:true,suppressInsecureJavaScriptEnvironmentWarning:true}});
const calls=[],renders=[];let selected='firstPdfFile123';const files=[{id:selected,name:'first.pdf'},{id:'latestPdfFile123',name:'latest.pdf'}];
try{window.document.write(fs.readFileSync('public/pdf.html','utf8').replace(/<script[\s\S]*?<\/script>/g,''));window.HTMLCanvasElement.prototype.getContext=()=>({});window.pdfTestLib={GlobalWorkerOptions:{},getDocument:()=>({destroy:async()=>{},promise:Promise.resolve({numPages:3,destroy:async()=>{},getPage:async page=>({getViewport:({scale})=>({width:600*scale,height:800*scale}),render:()=>{renders.push(page);return {promise:Promise.resolve(),cancel(){}};}})})})};window.fetch=async(input,options={})=>{const url=new URL(input,'https://hub.test');calls.push({path:url.pathname,fileId:url.searchParams.get('fileId'),method:options.method||'GET'});let data;if(url.pathname.endsWith('info'))data={files,defaultPdfId:selected,canManagePdf:true,canManagePdfPanel:false};else if(url.pathname.endsWith('star')){selected=JSON.parse(options.body).fileId;data={files,defaultPdfId:selected,selection:'starred'};}else if(url.pathname.endsWith('url'))data={url:'https://private.test/read.pdf',name:files.find(f=>f.id===url.searchParams.get('fileId')).name,fileId:url.searchParams.get('fileId')};else return {ok:true,blob:async()=>new window.Blob(['PDF'])};return {ok:true,json:async()=>data};};window.URL.createObjectURL=()=> 'blob:test';window.URL.revokeObjectURL=()=>{};window.HTMLAnchorElement.prototype.click=function(){this.clicked=true;};window.eval(fs.readFileSync('public/pdf-viewer.mjs','utf8').replace("await import('/pdfjs.mjs')",'window.pdfTestLib'));
const tick=async()=>{for(let i=0;i<8;i++)await new Promise(resolve=>setTimeout(resolve,0));};await tick();const $=id=>window.document.getElementById(id);
assert.equal($('manage').hidden,true);assert.equal($('file').value,selected);assert.equal($('canvas').hidden,false);assert.equal($('download').disabled,false);assert.equal($('fullscreen').disabled,false);assert.equal($('count').textContent,'/ 3');assert.equal($('fit'),null);assert.equal($('read-direction').tagName,'BUTTON');assert.equal(parseFloat($('canvas').style.width),window.innerWidth);assert.deepEqual(renders,[1]);assert.ok(!calls.some(c=>c.path==='/read.pdf'));
$('fullscreen').click();await tick();assert.ok(window.document.body.classList.contains('reading-mode'));assert.equal($('exit-fullscreen').hidden,false);assert.match(window.getComputedStyle($('stage')).backgroundColor,/#000|rgb\(0, 0, 0\)/);assert.equal(window.getComputedStyle($('page-tools')).visibility,'hidden');$('exit-fullscreen').click();await tick();assert.ok(!window.document.body.classList.contains('reading-mode'));
assert.equal($('fullscreen').parentElement.id,'pdf-sheet');$('canvas').dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true}));await tick();assert.ok(window.document.body.classList.contains('reading-mode'));$('canvas').dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true}));await tick();assert.ok(!window.document.body.classList.contains('reading-mode'));
const swipe=(x,y,endX,endY)=>{const start=new window.Event('touchstart',{bubbles:true});Object.defineProperty(start,'touches',{value:[{clientX:x,clientY:y}]});$('canvas').dispatchEvent(start);const end=new window.Event('touchend',{bubbles:true,cancelable:true});Object.defineProperty(end,'touches',{value:[]});Object.defineProperty(end,'changedTouches',{value:[{clientX:endX,clientY:endY}]});$('canvas').dispatchEvent(end);};swipe(180,100,50,100);await tick();assert.equal($('page-number').value,'2');swipe(50,100,180,100);await tick();assert.equal($('page-number').value,'1');swipe(100,180,100,50);await tick();assert.equal($('page-number').value,'1');swipe(100,50,100,180);await tick();assert.equal($('page-number').value,'1');
$('next').click();await tick();assert.equal($('page-number').value,'2');$('next').click();await tick();$('stage').scrollTop=123;swipe(180,100,50,100);await tick();assert.equal($('page-number').value,'3');assert.equal($('stage').scrollTop,123);$('previous').click();await tick();$('larger').click();await tick();assert.ok(renders.includes(2));swipe(180,100,50,100);await tick();assert.equal($('page-number').value,'2');$('file').value='latestPdfFile123';$('file').dispatchEvent(new window.Event('change'));await tick();assert.ok(calls.some(c=>c.fileId==='latestPdfFile123'));assert.equal($('star').disabled,false);$('star').click();await tick();assert.equal(selected,'latestPdfFile123');assert.equal($('star').disabled,true);assert.ok($('file').selectedOptions[0].textContent.startsWith('★'));
$('read-direction').click();await tick();assert.equal($('continuous').hidden,false);assert.equal($('canvas').hidden,true);assert.equal($('continuous').querySelectorAll('.pdf-page').length,3);const slots=[...$('continuous').children];slots.forEach((slot,index)=>Object.defineProperty(slot,'offsetTop',{configurable:true,value:index*parseFloat(slot.style.height)}));Object.defineProperty($('stage'),'clientHeight',{configurable:true,value:600});$('stage').scrollTop=parseFloat(slots[0].style.height)+100;$('stage').dispatchEvent(new window.Event('scroll'));await new Promise(r=>setTimeout(r,50));await tick();assert.equal($('page-number').value,'2');const continuousCanvas=slots[1].querySelector('canvas');continuousCanvas.dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true}));await tick();assert.ok(window.document.body.classList.contains('reading-mode'));$('continuous').querySelector('canvas').dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true}));await tick();assert.ok(!window.document.body.classList.contains('reading-mode'));$('read-direction').click();await tick();assert.equal($('continuous').hidden,true);assert.equal($('canvas').hidden,false);
$('download').click();await tick();assert.equal(calls.filter(c=>c.path==='/read.pdf').length,1);assert.ok(calls.filter(c=>c.path.endsWith('url')).length>=3);
console.log('PASS: Hub viewer renders selected PDF without automatic download, paginates/zooms, supports black fullscreen/double-click toggling and continuous vertical pages, switches files, saves default stars, and downloads only on click.');
}finally{window.happyDOM.abort();window.close();}
